### ISSUE TITLE
选择图片一启动就奔溃了...

### ISSUE THREAD

**Issue by azhon** [zhihu/Matisse#138]
Matisse.from(MyDataActivity.this)
                .choose(MimeType.allOf()) // 选择 mime 的类型
                .countable(true)
                .maxSelectable(1) // 图片选择的最多数量
                .gridExpectedSize(3)
                .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
                .thumbnailScale(0.85f) // 缩略图的比例
                .imageEngine(new GlideEngine()) // 使用的图片加载引擎
                .forResult(Constant.SELECT_IMAGE); // 设置作为标记的请求码

logcat： 
java.lang.IllegalArgumentException: Width and height must be Target#SIZE_ORIGINAL or > 0
    at com.bumptech.glide.GenericRequestBuilder.override(GenericRequestBuilder.java:564)
    at com.bumptech.glide.BitmapRequestBuilder.override(BitmapRequestBuilder.java:435)
    at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:39)
    at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
    at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
    at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapt
    at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerV
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.j
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Recy
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:22
    at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:59
    at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1697)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1551)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1460)
    at android.view.View.layout(View.java:14889)
    at android.view.ViewGroup.layout(ViewGroup.java:4651)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(Vie

**Comment by s1168805219** [comment]
在6.0系统上报错，在5.1.1上正常。 targetSdkVersion 22.错误log:
` FATAL EXCEPTION: main
                                                                   Process: com.cqc.matisse01, PID: 10879
                                                                   java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.cqc.matisse01-1/split_lib_dependencies_apk.apk:classes17.dex)
                                                                       at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:36)
                                                                       at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                       at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                       at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                       at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                       at android.view.View.layout(View.java:16658)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                   	at android.widget.FrameLayout.onLayout(`

**Comment by REBOOTERS** [comment]
What is Matisse version and glide version ?
