### ISSUE TITLE
android 5.1 (22)，OPPO:OPPO R9tm:arm64-v8a闪退

### ISSUE THREAD

**Issue by MaSiYuan** [zhihu/Matisse#149]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.zhihu.matisse.internal.entity.Item.isImage(Item.java:105)
	at com.zhihu.matisse.internal.entity.Item.<init>(Item.java:54)
	at com.zhihu.matisse.internal.entity.Item.valueOf(Item.java:79)
	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.getItemViewType(AlbumMediaAdapter.java:191)
	at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.getItemViewType(RecyclerViewCursorAdapter.java:54)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16065)
	at android.view.ViewGroup.layout(ViewGroup.java:5234)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)

**Comment by MaksimLiu** [comment]
I have the same problem

**Comment by congshengwu** [comment]
I have the same problem too.

**Comment by zk184174875** [comment]
return  MimeType.JPEG.equals(mimeType)
                || MimeType.PNG.toString().equals(mimeType)
                || MimeType.GIF.toString().equals(mimeType)
                || MimeType.BMP.toString().equals(mimeType)
                || MimeType.WEBP.toString().equals(mimeType);
//        return mimeType.equals(MimeType.JPEG.toString())
