### ISSUE TITLE
点击 预览 按钮时崩溃

### ISSUE THREAD

**Issue by kakayang2011** [zhihu/Matisse#187]
异常如下：

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gzsll.hupu/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.view.InflateException: Binary XML file line #35: Error inflating class TextView
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2561)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2635)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:188)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5739)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1039)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:834)
                                                                 Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class TextView
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                    at com.zhihu.matisse.internal.ui.BasePreviewActivity.onCreate(BasePreviewActivity.java:64)
                                                                    at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onCreate(AlbumPreviewActivity.java:42)
                                                                    at android.app.Activity.performCreate(Activity.java:6120)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2635) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:188) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5739) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1039) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:834) 
                                                                 Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 6
                                                                    at android.content.res.TypedArray.getColorStateList(TypedArray.java:438)
                                                                    at android.widget.TextView.<init>(TextView.java:882)
                                                                    at android.widget.TextView.<init>(TextView.java:803)
                                                                    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                    at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                    at com.zhihu.matisse.internal.ui.BasePreviewActivity.onCreate(BasePreviewActivity.java:64) 
                                                                    at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onCreate(AlbumPreviewActivity.java:42) 
                                                                    at android.app.Activity.performCreate(Activity.java:6120) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2508) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2635) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:188) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5739) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1039) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:834)

**Comment by missyoujigan** [comment]
你的应用theme不是集成的AppCompat Theme吧，需要你在manifeset中注册这个AlbumPreviewActivity，然后设置theme 为 AppCompat的theme

**Comment by wslaimin** [comment]
在你的app module的AndroidManifest的<application/>標籤指定theme
`<application
        android:name="com.addcn.car8891.model.service.CarApplication"
        android:allowBackup="true"
        android:hardwareAccelerated="false"
        android:icon="@mipmap/app_icon"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:theme="@style/Theme.Appcompat.Light.NoActionBar">`</application>
