### ISSUE TITLE
华为4.4 拍照点击对号直接相机崩溃

### ISSUE THREAD

**Issue by iammasir** [zhihu/Matisse#244]
11-08 11:12:07.905 8063-8063/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.huawei.camera, PID: 8063
                                                 java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{424c6660 8063:com.huawei.camera/u0a11} (pid=8063, uid=10011) that is not exported from uid 10137
                                                     at android.os.Parcel.readException(Parcel.java:1468)
                                                     at android.os.Parcel.readException(Parcel.java:1422)
                                                     at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2906)
                                                     at android.app.ActivityThread.acquireProvider(ActivityThread.java:4703)
                                                     at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2292)
                                                     at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1459)
                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:916)
                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:679)
                                                     at android.content.ContentResolver.openOutputStream(ContentResolver.java:655)
                                                     at com.huawei.camera.util.ActivityUtil.openOutputStream(ActivityUtil.java:72)
                                                     at com.huawei.camera.util.ActivityUtil.writeDataToUri(ActivityUtil.java:81)
                                                     at com.huawei.camera.ui.page.ReviewPage.handlePhotoDataResult(ReviewPage.java:117)
                                                     at com.huawei.camera.ui.page.ReviewPage.doReturnToCaller(ReviewPage.java:107)
                                                     at com.huawei.camera.ui.page.ReviewPage.access$000(ReviewPage.java:33)
                                                     at com.huawei.camera.ui.page.ReviewPage$1.onClick(ReviewPage.java:49)
                                                     at android.view.View.performClick(View.java:4457)
                                                     at android.view.View$PerformClick.run(View.java:18491)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by nevermore1000** [comment]
权限问题，是否拒绝了相关权限

**Comment by PantomZ** [comment]
我也遇到了，请问怎么解决的？

**Comment by PantomZ** [comment]
#274，改动试试
