### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by lawinko** [zhihu/Matisse#252]
```
11-15 04:01:05.629 3338-3338/com.mount.lawfirm E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.mount.lawfirm, PID: 3338
                                                                 java.lang.NullPointerException: Attempt to invoke interface method 'void com.zhihu.matisse.engine.ImageEngine.loadThumbnail(android.content.Context, int, android.graphics.drawable.Drawable, android.widget.ImageView, android.net.Uri)' on a null object reference
                                                                     at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                     at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                     at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                     at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                     at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                     at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                     at android.view.View.layout(View.java:15671)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:5038)
                                                                 	at android.vi
```

**Comment by sshnakamoto** [comment]
Have you fixed this? I'm facing same issue

**Comment by REBOOTERS** [comment]
issue had been fixed.
