### ISSUE TITLE
最新0.5.0-beta2预览报错

### ISSUE THREAD

**Issue by liompei** [zhihu/Matisse#266]
使用了gilde4.3.0 已经自定义了GlideAppEngine ,选择图片没问题,返回没问题,但是点击预览或者点开图片时就报以下错误
android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class it.sephiroth.android.library.imagezoom.ImageViewTouch
                                                                   Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class it.sephiroth.android.library.imagezoom.ImageViewTouch
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "it.sephiroth.android.library.imagezoom.ImageViewTouch" on path: DexPathList[[zip file "/data/app/com.bjletu.lelive-2/base.apk",

已经在Manifasr中注册了FileProvider
使用方式为:
 Matisse.from(CreateRoomActivity.this)
                                .choose(MimeType.ofImage())
                                .theme(R.style.Matisse_Dracula)
                                .countable(false)  //是否增加数字标记
                                .capture(true)
                                .captureStrategy(//参数1 true表示拍照存储在共有目录，false表示存储在私有目录；参数2与 AndroidManifest中authorities值相同，用于适配7.0系统 必须设置
                                        new CaptureStrategy(true, "com.bjletu.lelive.fileprovider"))
                                .maxSelectable(1)
                                .imageEngine(new GlideAppEngine())
                                .forResult(REQUEST_CODE_CHOOSE);

软件版本Android Studio 3.0.1,
    compileSdkVersion 27
    buildToolsVersion '27.0.1'

测试机型小米6 系统版本7.1.1

**Comment by DummyCo** [comment]
Ref #262 #264

**Comment by Jusenr** [comment]
双击item,崩溃。。。

` android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class it.sephiroth.android.library.imagezoom.ImageViewTouch
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:558)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:434)
                                                                        at com.zhihu.matisse.internal.ui.PreviewItemFragment.onCreateView(PreviewItemFragment.java:51)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:662)
                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:624)
                                                                        at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1078)
                                                                        at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3089)
                                                                        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284)
                                                                        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
                                                                        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
                                                                        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)
                                                                        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
                                                                        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
                                                                        at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                                        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                                        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                                        at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
                                                                        at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
                                                                        at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
                                                                        at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:150)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class it.sephiroth.android.library.imagezoom.ImageViewTouch
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:795)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:723)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:817)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:434) 
                                                                        at com.zhihu.matisse.internal.ui.PreviewItemFragment.onCreateView(PreviewItemFragment.java:51) 
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809) 
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799) 
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580) 
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367) 
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322) 
                                                                        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199) 
                                                                        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651) 
                                                                        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145) 
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1236) 
                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:662) 
                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:624) 
                                                                        at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1078) 
                                                                        at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3089) 
                                                                        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:284) 
                                                                        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71) 
                                                                        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64) 
                                                                        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33) 
                                                                        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476) 
                                                                        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444) 
                                                                        at android.support.v4.content.Loader.deliverResult(Loader.java:126) 
                                                                        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105) 
                                                                        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37) 
                                                                        at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255) 
                                                                        at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80) 
                                                                        at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487) 
                                                                        at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:150) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5621) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "it.sephiroth.android.library.imagezoom.ImageViewTouch" on path: DexPathList[[zip file "/data/app/com.ju`

**Comment by gejiaheng** [comment]
For further information:
bintray-release didn't handle implementation/api dependency scopes after upgrading to android gradle plugin 3.0. The generated pom.xml file missed dependency attrs. The latest bintray-release tool fixed it.

**Comment by littlehome-eugene** [comment]
we get this error if we build lib with `./gradlew assemble` 

how should we build the lib?
