### ISSUE TITLE
小米4C 0.5.0-beta2拍照闪退

### ISSUE THREAD

**Issue by hdhhdhd** [zhihu/Matisse#275]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.administrator.mitessdemo/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class TextView
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:163)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6326)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                                                       Caused by: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class TextView
                                                                                       Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class TextView
                                                                                       Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f010002 a=-1}
                                                                                          at android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
                                                                                          at android.widget.TextView.<init>(TextView.java:1076)
                                                                                          at android.widget.TextView.<init>(TextView.java:704)
                                                                                          at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                                          at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                                          at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1026)
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1083)
                                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
                                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
                                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
                                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
                                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                          at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:90)
                                                                                          at android.app.Activity.performCreate(Activity.java:6847)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:163)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6326)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by hdhhdhd** [comment]
已经解决，是因为app的主题、app的xml代码、系统的默认attr都没有指定textColor所以会报错

**Comment by ethanhua** [comment]
@hdhhdhd 你好 你是怎么解决的？我使用的是默认的知乎主题
