### ISSUE TITLE
Application crash when use glide 4.4.0

### ISSUE THREAD

**Issue by anas-najjar** [zhihu/Matisse#290]
Matisse.from(this)
                    .choose(MimeType.of(MimeType.JPEG,MimeType.PNG))
                    .countable(true)
                    .maxSelectable(MAX_SIZE)
                    .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                    .thumbnailScale(0.85f)
                    .forResult(IMAGES_PICKER);

following the log:
java.lang.NullPointerException: Attempt to invoke interface method 'void com.zhihu.matisse.engine.ImageEngine.loadThumbnail(android.content.Context, int, android.graphics.drawable.Drawable, android.widget.ImageView, android.net.Uri)' on a null object reference
                                                                    at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                    at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                    at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                    at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                    at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                    at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                    at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                    at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
12-21 11:37:54.586 12641-12641/com.harri.team E/AndroidRuntime:     at android.view.View.layout(View.java:19659)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                    at android.os.Handler.handleCallback(Handler.java:790)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

when I change the imageEngine as this 
 Matisse.from(this)
                    .choose(MimeType.of(MimeType.JPEG,MimeType.PNG))
                    .countable(true)
                    .maxSelectable(MAX_SIZE)
                    .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                    .thumbnailScale(0.85f)
                    .imageEngine(new PicassoEngine())
                    .forResult(IMAGES_PICKER);

it crashed also following the log

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/picasso/Picasso;
                                                                         at com.zhihu.matisse.engine.impl.PicassoEngine.loadThumbnail(PicassoEngine.java:34)
                                                                         at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                         at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                         at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                         at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
                                                                         at android.view.View.layout(View.java:19659)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:6075)
12-21 11:33:15.147 11892-11892/com.harri.team E/Harri-TeamCloud.com:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                         at android.os.Handler.handleCallback(Handler.java:790)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.picasso.Picasso" on path: DexPathList[[zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/base.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_dependencies_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_0_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_1_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_2_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_3_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_4_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_5_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_6_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_7_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_8_apk.apk", zip file "/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.harri.team-8acXMJCbz5cDrSFX_DJn6g==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                         	... 70 more

**Comment by CzSam** [comment]
You can use a custom engine with Glide 4.0+
like this
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.net.Uri;
import android.widget.ImageView;

import com.bumptech.glide.Glide;
import com.bumptech.glide.Priority;
import com.bumptech.glide.request.RequestOptions;
import com.zhihu.matisse.engine.ImageEngine;

/**
 * Created by Administrator on 2017/12/25.
 * Matisse图片引擎
 */

public class Glide4Engine implements ImageEngine
{

    @Override
    public void loadThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView, Uri uri)
    {
        GlideApp.with(context)
                .asBitmap()  // some .jpeg files are actually gif
                .load(uri)
                .apply(new RequestOptions()
                        .placeholder(placeholder)
                        .override(resize, resize)
                        .centerCrop())
                .into(imageView);
    }

    @Override
    public void loadAnimatedGifThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView, Uri uri)
    {
        GlideApp.with(context)
                .asBitmap()
                .load(uri)
                .apply(new RequestOptions()
                        .placeholder(placeholder)
                        .override(resize, resize)
                        .centerCrop())
                .into(imageView);
    }

    @Override
    public void loadImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri)
    {
        GlideApp.with(context)
                .load(uri)
                .apply(new RequestOptions()
                        .override(resizeX, resizeY)
                        .priority(Priority.HIGH))
                .into(imageView);
    }

    @Override
    public void loadAnimatedGifImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri)
    {
        GlideApp.with(context)
                .asGif()
                .load(uri)
                .apply(new RequestOptions()
                        .override(resizeX, resizeY)
                        .priority(Priority.HIGH))
                .into(imageView);
    }

    @Override
    public boolean supportAnimatedGif()
    {
        return true;
    }
}

**Comment by anas-najjar** [comment]
Thanks CzSam it worked

**Comment by NikoMontana** [comment]
This worked like a charm! Thank you @anas-najjar, great work!

**Comment by REBOOTERS** [comment]
For glide V4+ : https://github.com/zhihu/Matisse#for-glide-v4
