### ISSUE TITLE
红米Note拍照挂掉了

### ISSUE THREAD

**Issue by cxmmxc** [zhihu/Matisse#30]
> captureStrategy(new CaptureStrategy(true, "com.zhihu.matisse.sample.fileprovider"))这是我拍照的代码

```com.zhihu.matisse.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.zhihu.matisse.sample, PID: 18814
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhihu.matisse.sample/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class TextView
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                           Caused by: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class TextView
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                              at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:83)
                                                                              at android.app.Activity.performCreate(Activity.java:6303)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class TextView
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:786)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:83) 
                                                                              at android.app.Activity.performCreate(Activity.java:6303) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                           Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f010004 a=-1}
                                                                              at android.content.res.TypedArray.getColorStateList(TypedArray.java:484)
                                                                              at android.widget.TextView.<init>(TextView.java:1046)
                                                                              at android.widget.TextView.<init>(TextView.java:674)
                                                                              at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                              at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                              at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                              at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:83) 
                                                                              at android.app.Activity.performCreate(Activity.java:6303) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) ```

**Comment by cxmmxc** [comment]
这个问题解决了，由于横竖屏切换导致的，加上android:configChanges="orientation|screenSize|keyboardHidden"属性就OK了
不过我刚拍的照片，然后在进入图片选择器，竟然没有刚拍的照片；
这算个bug吧。。。。

**Comment by gejiaheng** [comment]
@cxmmxc 
Thanks for reporting this. Capture feature is still under development and I will have a look at this issue.

**Comment by woniu0936** [comment]
@cxmmxc 是在你使用这个库的页面对应的activity的manifests里面添加android:configChanges="orientation|screenSize|keyboardHidden"，还是在这个库的源码里面的MatisseActivity的manifests里面添加android:configChanges="orientation|screenSize|keyboardHidden"

**Comment by cxyhegithub** [comment]
@cxmmxc 我换上android:configChanges="orientation|screenSize|keyboardHidden"这句话后app还是闪退
