### ISSUE TITLE
在另一进程的Activity打开图库白屏报Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by xuhaoyang** [zhihu/Matisse#300]
如题，现在有个需求是Activity需要跑Webview，内存消耗过大，将这个Activity设置了android:process另一个进程启动，之后再启动图库会报错，但如果在app中androidmanifest设置了复写了Activity并配置了一样的android:process，则不会出现白屏问题。

报错日志没抓到，但是腾讯的bugly抓到部分信息

```

java.lang.RuntimeException:Unable to start activity ComponentInfo{hk.xhy.demo/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class TextView
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)

4 Caused by:
5 java.lang.UnsupportedOperationException:Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040026 a=-1}
6 android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
7 android.content.res.XResources$XTypedArray.getColorStateList(XResources.java:1309)
8 android.widget.TextView.<init>(TextView.java:1076)
9 android.widget.TextView.<init>(TextView.java:704)
10 android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:75)
11 android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
12 android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
13 android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
14 android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
15 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
16 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
17 android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
18 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
19 android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
20 android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
21 android.view.LayoutInflater.inflate(LayoutInflater.java:522)
22 de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
23 de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
24 android.view.LayoutInflater.inflate(<Xposed>)
25 android.view.LayoutInflater.inflate(LayoutInflater.java:430)
26 android.view.LayoutInflater.inflate(LayoutInflater.java:377)
27 android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
28 android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
29 com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:90)
30 android.app.Activity.performCreate(Activity.java:6847)
31 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
32 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
33 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
34 android.app.ActivityThread.-wrap12(ActivityThread.java)
35 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
36 android.os.Handler.dispatchMessage(Handler.java:102)
37 android.os.Looper.loop(Looper.java:163)
38 android.app.ActivityThread.main(ActivityThread.java:6321)
39 java.lang.reflect.Method.invoke(Native Method)
40 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
41 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

```

**Comment by Timelessx** [comment]
遇到了同样的问题，这样配置就可以了
 **<activity android:name="com.zhihu.matisse.ui.MatisseActivity" android:multiprocess="true" />** 

错误日志如下：

AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{你的进程名/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class TextView
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
   at android.app.ActivityThread.access$800(ActivityThread.java:151)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5254)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class TextView
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
   at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:90)
   at android.app.Activity.performCreate(Activity.java:5990)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
   at android.app.ActivityThread.access$800(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:135) 
   at android.app.ActivityThread.main(ActivityThread.java:5254) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:372) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 5
   at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
   at android.widget.TextView.<init>(TextView.java:991)
   at android.widget.TextView.<init>(TextView.java:632)
   at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
   at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
   at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
   at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
   at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
   at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
   at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:90) 
   at android.app.Activity.performCreate(Activity.java:5990) 
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
   at android.app.ActivityThread.access$800(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:135) 
   at android.app.ActivityThread.main(ActivityThread.java:5254) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:372) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by xuhaoyang** [comment]
@Timelessx thk
