### ISSUE TITLE
 No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class 

### ISSUE THREAD

**Issue by Allyns** [zhihu/Matisse#316]
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.szcx.tomatoaspect-2/split_lib_dependencies_apk.apk)

**Comment by chihung93** [comment]
me too.
Android 6.0
Device : Zenfone 


01-15 05:37:52.615 20842-20842/com.okadabooks.mock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.okadabooks.mock, PID: 20842
                                                                     java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.okadabooks.mock-1/base.apk:classes3.dex)
                                                                         at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:36)
                                                                         at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                         at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                         at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                         at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16647)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5438)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                     	at android.widget.FrameLayout.onLayout(FrameLayout.java:27

**Comment by HuanTanSheng** [comment]
@Allyns @chihung93 
这个错误是由于Glide版本冲突导致的，Matisse依赖的是glide:3.7.0，而你们使用的是glide:4.x。
当然，也有可能是你们依赖的其他三方库依赖了glide:4.x版本。
建议统一Glide版本。
或者可以使用我的同类框架[EasyPhotos](https://github.com/HuanTanSheng/EasyPhotos)，它以接口的形式绑定图片加载库，所以不会出现类似问题。

**Comment by Allyns** [comment]
这个问题      .imageEngine(new MyGlideEngine())   自定义GlideEngine就可以了

**Comment by Allyns** [comment]
public class MyGlideEngine implements ImageEngine {

    @Override
    public void loadThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView, Uri uri) {
        RequestOptions requestOptions = new RequestOptions()
                .override(resize, resize)
                .centerCrop()
                .placeholder(placeholder);
        Glide.with(context)
                .asBitmap()
                .load(uri)
                .apply(requestOptions)
                .into(imageView);
    }

    @Override
    public void loadAnimatedGifThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView,
                                         Uri uri) {
        RequestOptions requestOptions = new RequestOptions()
                .override(resize, resize)
                .centerCrop()
                .placeholder(placeholder);
        Glide.with(context)
                .asBitmap()
                .load(uri)
                .apply(requestOptions)
                .into(imageView);
    }

    @Override
    public void loadImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
        RequestOptions requestOptions = new RequestOptions()
                .override(resizeX, resizeY)
                .priority(Priority.HIGH)
                .centerCrop();
        Glide.with(context)
                .load(uri)
                .apply(requestOptions)
                .into(imageView);
    }

    @Override
    public void loadAnimatedGifImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
        RequestOptions requestOptions = new RequestOptions()
                .override(resizeX, resizeY)
                .priority(Priority.HIGH)
                .centerCrop();
        Glide.with(context)
                .asGif()
                .load(uri)
                .apply(requestOptions)
                .into(imageView);
    }

    @Override
    public boolean supportAnimatedGif() {
        return true;
    }

}

**Comment by sshnakamoto** [comment]
As @Allyns suggests use this:

```java
public class MyGlideEngine implements ImageEngine {

@Override
public void loadThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView, Uri uri) {
    RequestOptions requestOptions = new RequestOptions()
            .override(resize, resize)
            .centerCrop()
            .placeholder(placeholder);
    Glide.with(context)
            .asBitmap()
            .load(uri)
            .apply(requestOptions)
            .into(imageView);
}

@Override
public void loadAnimatedGifThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView,
                                     Uri uri) {
    RequestOptions requestOptions = new RequestOptions()
            .override(resize, resize)
            .centerCrop()
            .placeholder(placeholder);
    Glide.with(context)
            .asBitmap()
            .load(uri)
            .apply(requestOptions)
            .into(imageView);
}

@Override
public void loadImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
    RequestOptions requestOptions = new RequestOptions()
            .override(resizeX, resizeY)
            .priority(Priority.HIGH)
            .centerCrop();
    Glide.with(context)
            .load(uri)
            .apply(requestOptions)
            .into(imageView);
}

@Override
public void loadAnimatedGifImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
    RequestOptions requestOptions = new RequestOptions()
            .override(resizeX, resizeY)
            .priority(Priority.HIGH)
            .centerCrop();
    Glide.with(context)
            .asGif()
            .load(uri)
            .apply(requestOptions)
            .into(imageView);
}

@Override
public boolean supportAnimatedGif() {
    return true;
}

} 
```

On this:

```java
Matisse.from(MainActivity.this)
            .choose(MimeType.of(MimeType.JPEG, MimeType.PNG))
            .countable(true)
            .theme(R.style.Matisse_Dracula)
            .gridExpectedSize(getResources().getDimensionPixelSize(R.dimen.grid_expected_size))
            .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
            .thumbnailScale(0.85f)
            .imageEngine(new MyGlideEngine())
            .forResult(REQUEST_CODE_CHOOSE);
```

**Comment by sondevelopervn** [comment]
> As @Allyns suggests use this:
> 
> ```java
> public class MyGlideEngine implements ImageEngine {
> 
> @Override
> public void loadThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView, Uri uri) {
>     RequestOptions requestOptions = new RequestOptions()
>             .override(resize, resize)
>             .centerCrop()
>             .placeholder(placeholder);
>     Glide.with(context)
>             .asBitmap()
>             .load(uri)
>             .apply(requestOptions)
>             .into(imageView);
> }
> 
> @Override
> public void loadAnimatedGifThumbnail(Context context, int resize, Drawable placeholder, ImageView imageView,
>                                      Uri uri) {
>     RequestOptions requestOptions = new RequestOptions()
>             .override(resize, resize)
>             .centerCrop()
>             .placeholder(placeholder);
>     Glide.with(context)
>             .asBitmap()
>             .load(uri)
>             .apply(requestOptions)
>             .into(imageView);
> }
> 
> @Override
> public void loadImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
>     RequestOptions requestOptions = new RequestOptions()
>             .override(resizeX, resizeY)
>             .priority(Priority.HIGH)
>             .centerCrop();
>     Glide.with(context)
>             .load(uri)
>             .apply(requestOptions)
>             .into(imageView);
> }
> 
> @Override
> public void loadAnimatedGifImage(Context context, int resizeX, int resizeY, ImageView imageView, Uri uri) {
>     RequestOptions requestOptions = new RequestOptions()
>             .override(resizeX, resizeY)
>             .priority(Priority.HIGH)
>             .centerCrop();
>     Glide.with(context)
>             .asGif()
>             .load(uri)
>             .apply(requestOptions)
>             .into(imageView);
> }
> 
> @Override
> public boolean supportAnimatedGif() {
>     return true;
> }
> 
> } 
> ```
> 
> On this for example:
> 
> ```java
> Matisse.from(MainActivity.this)
>             .choose(MimeType.of(MimeType.JPEG, MimeType.PNG))
>             .countable(true)
>             .theme(R.style.Matisse_Dracula)
>             .gridExpectedSize(getResources().getDimensionPixelSize(R.dimen.grid_expected_size))
>             .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
>             .thumbnailScale(0.85f)
>             .imageEngine(new MyGlideEngine())
>             .forResult(REQUEST_CODE_CHOOSE);
> ```

Ok, Thank you
