### ISSUE TITLE
java.lang.NullPointerException:

### ISSUE THREAD

**Issue by skylarliuu** [zhihu/Matisse#334]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
     	at com.zhihu.matisse.internal.entity.Item.isGif(Item.java:91)
     	at com.zhihu.matisse.internal.ui.PreviewItemFragment.onActivityCreated(PreviewItemFragment.java:59)
     	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2201)
     	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
     	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
     	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
     	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
     	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
     	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
     	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
     	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
     	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
     	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
     	at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
     	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
     	at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
     	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:921)
     	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
     	at android.view.Choreographer.doFrame(Choreographer.java:655)
     	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:907)
     	at android.os.Handler.handleCallback(Handler.java:836)
     	at android.os.Handler.dispatchMessage(Handler.java:103)
     	at android.os.Looper.loop(Looper.java:203)
     	at android.app.ActivityThread.main(ActivityThread.java:6406)
     	at java.lang.reflect.Method.invoke(Native Method)
     	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by REBOOTERS** [comment]
the bug had been fixed at release 0.5.x
