### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by skylarliuu** [zhihu/Matisse#335]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wiserz.pbibi/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class TextView
     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2853)
     	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
     	at android.app.ActivityThread.-wrap12(ActivityThread.java)
     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
     	at android.os.Handler.dispatchMessage(Handler.java:110)
     	at android.os.Looper.loop(Looper.java:203)
     	at android.app.ActivityThread.main(ActivityThread.java:6406)
     	at java.lang.reflect.Method.invoke(Native Method)
     	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
     Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class TextView
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f030031 a=-1}
     	at android.content.res.TypedArray.getColorStateList(TypedArray.java:531)
     	at android.widget.TextView.<init>(TextView.java:1123)
     	at android.widget.TextView.<init>(TextView.java:752)
     	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
     	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
     	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
     	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
     	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
     	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
     	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
     	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
     	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
     	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
     	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
     	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
     	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
     	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
     	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
     	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
     	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
     	at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:83)
     	at android.app.Activity.performCreate(Activity.java:6758)
     	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
     	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
     	at android.app.ActivityThread.-wrap12(ActivityThread.java)
     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
     	at android.os.Handler.dispatchMessage(Handler.java:110)
     	at android.os.Looper.loop(Looper.java:203)
     	at android.app.ActivityThread.main(ActivityThread.java:6406)
     	at java.lang.reflect.Method.invoke(Native Method)
     	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by REBOOTERS** [comment]
latest version fixed .
