### ISSUE TITLE
NullPointerException 锤子手机

### ISSUE THREAD

**Issue by idic779** [zhihu/Matisse#351]
Process: com.example.administrator.viewdemodick, PID: 14488
                                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                            at com.zhihu.matisse.internal.entity.Item.isGif(Item.java:91)
                                                                                            at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setGifTag(PhotoGrid.java:88)
                                                                                            at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:78)

锤子7.1系统，某个文件的mimeType 是空的，导致页面直接挂了

**Comment by Huangsn** [comment]
我也是这个问题.不知道怎么解决

**Comment by idic779** [comment]
@Huangsn  很奇葩，目测是锤子的问题，之后重启，一段时间可以了，不是重启立刻会生效

**Comment by REBOOTERS** [comment]
@idic779 @Huangsn   the latest version had fixed this issue .
