### ISSUE TITLE
UnsupportedOperationException crash reported from production!

### ISSUE THREAD

**Issue by ankitbatra11** [zhihu/Matisse#352]
Matisse occasionally throws up this error in the production instance of my app:

```
Caused by java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040027 a=-1}
       at android.content.res.TypedArray.getColorStateList(TypedArray.java:531)
       at android.widget.TextView.(TextView.java:1103)
       at android.widget.TextView.(TextView.java:732)
       at android.support.v7.widget.AppCompatTextView.(AppCompatTextView.java:76)
       at android.support.v7.widget.AppCompatTextView.(AppCompatTextView.java:72)
       at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
       at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
       at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:83)
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

How I use Matisse?
```
/**
 * @author abatra
 */
class MatissePicker implements Picker {

    private static final int SPAN_COUNT = 3;

    @Nullable
    private PickerListener pickerListener;

    @Override
    public void setPickerListener(@Nullable PickerListener pickerListener) {
        this.pickerListener = pickerListener;
    }

    @Override
    public boolean handleActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        switch (requestCode) {
            case Constants.REQ_CODE_PICK_MANY_IMAGES:
                break;
            default:
                return false;
        }
        if (pickerListener != null) {
            List<Uri> result = new ArrayList<>();
            if (resultCode == Activity.RESULT_OK && data != null) {
                List<Uri> uris = Matisse.obtainResult(data);
                if (uris != null && !uris.isEmpty()) {
                    result.addAll(uris);
                } else {
                    String message = "Uri list is empty even with OK result code and non null data!";
                    Timber.e(new RuntimeException(message));
                }
                if (!result.isEmpty()) {
                    pickerListener.onMediaPicked(result);
                }
            }
        }
        return true;
    }

    @Override
    public void pickMany(Fragment fragment) {
        prepareManyRequest(Matisse.from(fragment));
    }

    @Override
    public void pickMany(Activity activity) {
        prepareManyRequest(Matisse.from(activity));
    }

    private void prepareManyRequest(Matisse matisse) {
        matisse.choose(MimeType.allOf())
                .countable(true)
                .maxSelectable(Integer.MAX_VALUE)
                .spanCount(SPAN_COUNT)
                .imageEngine(new GlideEngine())
                .forResult(Constants.REQ_CODE_PICK_MANY_IMAGES);
    }
}
```

**Comment by REBOOTERS** [comment]
latest version fixed.
