### ISSUE TITLE
NullPointerException crash reported from production!

### ISSUE THREAD

**Issue by ankitbatra11** [zhihu/Matisse#353]
Matisse occasionally throws up this error in the production instance of my app:

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
       at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:50)
       at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:28)
       at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
       at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

How I use Matisse?

```
/**
 * @author abatra
 */
class MatissePicker implements Picker {

    private static final int SPAN_COUNT = 3;

    @Nullable
    private PickerListener pickerListener;

    @Override
    public void setPickerListener(@Nullable PickerListener pickerListener) {
        this.pickerListener = pickerListener;
    }

    @Override
    public boolean handleActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        switch (requestCode) {
            case Constants.REQ_CODE_PICK_MANY_IMAGES:
                break;
            default:
                return false;
        }
        if (pickerListener != null) {
            List<Uri> result = new ArrayList<>();
            if (resultCode == Activity.RESULT_OK && data != null) {
                List<Uri> uris = Matisse.obtainResult(data);
                if (uris != null && !uris.isEmpty()) {
                    result.addAll(uris);
                } else {
                    String message = "Uri list is empty even with OK result code and non null data!";
                    Timber.e(new RuntimeException(message));
                }
                if (!result.isEmpty()) {
                    pickerListener.onMediaPicked(result);
                }
            }
        }
        return true;
    }

    @Override
    public void pickMany(Fragment fragment) {
        prepareManyRequest(Matisse.from(fragment));
    }

    @Override
    public void pickMany(Activity activity) {
        prepareManyRequest(Matisse.from(activity));
    }

    private void prepareManyRequest(Matisse matisse) {
        matisse.choose(MimeType.allOf())
                .countable(true)
                .maxSelectable(Integer.MAX_VALUE)
                .spanCount(SPAN_COUNT)
                .imageEngine(new GlideEngine())
                .forResult(Constants.REQ_CODE_PICK_MANY_IMAGES);
    }
}
```

**Comment by REBOOTERS** [comment]
this issue had been fixed .

**Comment by REBOOTERS** [comment]
latest version
