### ISSUE TITLE
我用了glide4.6.1

### ISSUE THREAD

**Issue by liumingmad** [zhihu/Matisse#364]
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.dfs168.ttxn-cXFwl7okLTkW8FHbv7Vczg==/split_lib_dependencies_apk.apk)
        at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:36)
        at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
        at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
        at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
        at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)

**Comment by bluefish625** [comment]
不支持4.6.1，他们好像支持到3.7.0

**Comment by KelvinPac** [comment]
Am getting the same issue too. Affecting the whole app as I have to use older versions now

**Comment by Jakemesdg** [comment]
楼主除了用低版本还有别的方法吗？

**Comment by liumingmad** [comment]
@Jakemesdg 换成其他的库，如果一定要用Matisse，可能把代码clone下来，直接引用工程

**Comment by Jakemesdg** [comment]
@liumingmad 看了其他人提的issue，换一个引擎就可以解决了

**Comment by REBOOTERS** [comment]
使用 Glide V4+ 的用户请参考  https://github.com/zhihu/Matisse#for-glide-v4

**Comment by ksc91u** [comment]
How about use different branch, artifacts ?

Like this, 
https://jitpack.io/#ksc91u/Matisse

Contains two branches, master for glide 3, glide4 for glide 4.
