### ISSUE TITLE
Unable to start activity ComponentInfo{cn.eeepay.superchange/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class TextView

### ISSUE THREAD

**Issue by zhuangzeqin** [zhihu/Matisse#365]
Unable to start activity ComponentInfo{cn.eeepay.superchange/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class TextView

**Comment by AlphaGao1993** [comment]
matisse 里面很多 view 组件都是从 theme 里面去拿属性设置的，检查一下你的自定义 theme 吧

**Comment by bhijuelos** [comment]
Is this bug fixed in the latest version ?

**Comment by REBOOTERS** [comment]
yes

**Comment by RoboForgeStudios** [comment]
MatisseActivity.java line 107
com.zhihu.matisse.ui.MatisseActivity.onCreate

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ringapp/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class TextView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)


73% Xiaomi
18% Vertex
9% samsung

73% Android 9
18% Android 7
9% Android 6


`// Matisse
implementation 'com.zhihu.android:matisse:0.5.3-beta3'`

**Comment by RauanSatanbek** [comment]
`    // Matisse
    implementation 'com.zhihu.android:matisse:0.5.3-beta3'`
