### ISSUE TITLE
4.4闪退

### ISSUE THREAD

**Issue by WangChangQin** [zhihu/Matisse#368]
`FATAL EXCEPTION: ModernAsyncTask #1
                                                                          Process: com.changqin.schoolculture, PID: 5429
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                              at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                           Caused by: java.lang.NullPointerException
                                                                              at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:50)
                                                                              at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:28)
                                                                              at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
                                                                              at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
                                                                              at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
                                                                              at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                              at java.lang.Thread.run(Thread.java:841) 
`

**Comment by sxd-github** [comment]
拍照功能对4.4不兼容
