### ISSUE TITLE
Crash RuntimeException: Failed to resolve attribute at index 5

### ISSUE THREAD

**Issue by nguyenvp08** [zhihu/Matisse#377]
Can you guys help to fix this crash, I used your library just 1 month ago, The layout is beautiful but this crash occurred from your MatisseActivity, Maybe it's the problem with new gradle (3.1.0) with Aapt2 ? 
Do you know how to fix? I see many persons got this crash. Can you guys reply my problem.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mingle.fem/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class TextView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
       at android.app.ActivityThread.access$800(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5376)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

Caused by java.lang.RuntimeException: Failed to resolve attribute at index 5
       at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
       at android.widget.TextView.<init>(TextView.java:1032)
       at android.widget.TextView.<init>(TextView.java:674)
       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:75)
       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
       at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
       at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:90)

**Comment by TJBlack31** [comment]
@nguyenvp08   Did you try updating Gradle?

**Comment by nguyenvp08** [comment]
hi @TJBlack31 I currently using gradle version 3.1.1 with Android Studio 3.1.1, and the version of Matisse is 0.5.0-beta3

**Comment by ethanhua** [comment]
@nguyenvp08 I met this problem too. Have you solved it yet?

**Comment by nguyenvp08** [comment]
@ethanhua You should import the project and replace the base theme, attributes, and fix bug cause this project maybe no longer supported

**Comment by REBOOTERS** [comment]
please use lasted version  0.5.0-beta9
