### ISSUE TITLE
FileProvider NullPointerException

### ISSUE THREAD

**Issue by Ryokooo** [zhihu/Matisse#381]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                    at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                    at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                    at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)

**Comment by Novice9527** [comment]
解决了吗 有什么好的方法

**Comment by marcinkunert** [comment]
Make sure you have a file provider declared in AndroidManifest.xml
```
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.zhihu.matisse.sample.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths_public"></meta-data>
        </provider>
```

Use the sample app for reference: https://github.com/zhihu/Matisse/tree/master/sample
