### ISSUE TITLE
Crash when the activity is recreated

### ISSUE THREAD

**Issue by hegazy** [zhihu/Matisse#388]
The app was on background and after reopening it, the app just crashed. It looks like something went wrong when recreating the activity.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.circula.dev/com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #33: Binary XML file line #33: Error inflating class TextView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
OS Version: 8.1.0
Device: Pixel

Please see the attached file for more details on the issue
[crash.txt](https://github.com/zhihu/Matisse/files/2013816/crash.txt)

**Comment by REBOOTERS** [comment]
please try with lasted version  0.5.0-beta9
