### ISSUE TITLE
oppo手机NullPointerException

### ISSUE THREAD

**Issue by Charles-zhangchao** [zhihu/Matisse#401]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.zhihu.matisse.internal.entity.Item.isImage(Item.java:105)
	at com.zhihu.matisse.internal.entity.Item.<init>(Item.java:54)
	at com.zhihu.matisse.internal.entity.Item.valueOf(Item.java:79)
	at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.getItemViewType(AlbumMediaAdapter.java:191)
	at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.getItemViewType(RecyclerViewCursorAdapter.java:54)
	at

**Comment by zk184174875** [comment]
return  MimeType.JPEG.equals(mimeType)
                || MimeType.PNG.toString().equals(mimeType)
                || MimeType.GIF.toString().equals(mimeType)
                || MimeType.BMP.toString().equals(mimeType)
                || MimeType.WEBP.toString().equals(mimeType);
//        return mimeType.equals(MimeType.JPEG.toString())
