### ISSUE TITLE
0.5.1奔溃java.lang.NoSuchMethodError,具体看log

### ISSUE THREAD

**Issue by qianshengta** [zhihu/Matisse#420]
```
06-28 10:58:58.402 17382-17382/com.qian.lib.utils E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qian.lib.utils, PID: 17382
    java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.qian.lib.utils-1/split_lib_dependencies_apk.apk)
        at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:36)
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.setImage(MediaGrid.java:117)
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.bindMedia(MediaGrid.java:84)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onBindViewHolder(AlbumMediaAdapter.java:122)
        at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:45)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1764)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1607)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1516)
        at android.view.View.layout(View.java:16754)
        at android.view.ViewGroup.layout(ViewGroup.java:5462)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:338)
    	at android.widget.FrameLayout.onLayout(FrameLayout.ja
```

**Comment by REBOOTERS** [comment]
请问你使用的 Glide 版本是多少呢？

**Comment by qianshengta** [comment]
4.7.1，跟库里的最新版本一样？是不是现在还不支持4.x？是否应该考虑下放弃3.x改支持4.x，比较现在4.x应该是主流？

**Comment by REBOOTERS** [comment]
Matisse 内部的GlideEngine 是依赖与Glide V3 .所以你使用Glide V4的话 ，需要自己实现 GlideEngine 。具体参见 README 。

鉴于还有一部分人还在使用Glide V3 ，需要这样一个过渡期吧。Glide V3 到 V4 自身部分API 变化较大，也是无奈的事情。
