### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by zhangman523** [zhihu/Matisse#422]
特殊机型报错，魅蓝Note5
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    	at com.zhihu.matisse.internal.entity.Item.isGif(Item.java:91)
    	at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setGifTag(PhotoGrid.java:88)
    	at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:78)
    	at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
    	at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
    	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
    	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
    	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
    	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
    	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
    	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
    	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
    	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
    	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
    	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
    	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
    	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
    	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)`

**Comment by zhangman523** [comment]
@jollychang

**Comment by REBOOTERS** [comment]
Which version happened ?

**Comment by WratK** [comment]
@REBOOTERS same exception on 0.4.3

**Comment by WratK** [comment]
@REBOOTERS com.zhihu.matisse.internal.entity.Item$mimeType is null

**Comment by zhangman523** [comment]
@REBOOTERS  0.4.3

**Comment by REBOOTERS** [comment]
try with latest version ,the bug had been fixed.

**Comment by zhangman523** [comment]
@REBOOTERS ok, thanks!
