### ISSUE TITLE
Video预览，打开相册，返回应用就会崩溃

### ISSUE THREAD

**Issue by Rayhahah** [zhihu/Matisse#430]
java.lang.RuntimeException: Unable to resume activity {com.theon.videowallpaper/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3726)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3766)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
        at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
        at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:248)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:188)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:173)
        at android.support.v4.content.Loader.deliverResult(Loader.java:130)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:107)
        at android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:153)
        at android.support.v4.content.Loader.startLoading(Loader.java:283)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:76)
        at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
        at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
        at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
        at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
        at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
        at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
        at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
        at android.app.Fragment.performStart(Fragment.java:2534)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2984)
        at android.app.FragmentController.dispatchStart(FragmentController.java:189)
        at android.app.Activity.performStart(Activity.java:7062)
        at android.app.Activity.performRestart(Activity.java:7131)
        at android.app.Activity.performResume(Activity.java:7136)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3700)
        	... 8 more

**Comment by REBOOTERS** [comment]
#423
