### ISSUE TITLE
设置maxcount为9，当选中了9个，继续去点击选中第10个时，崩溃

### ISSUE THREAD

**Issue by ganzhubing** [zhihu/Matisse#446]
**Describe the bug**
设置maxcount为9，当选中了9个，继续去点击选中第10个时，崩溃

**Smartphone (please complete the following information):**
Android 6.0

**异常信息
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals

**Comment by REBOOTERS** [comment]
Need more info .
which version ?  what kind of device ?  It seems only happened on some unusual devices .  
If possible ,please show me how do you construct Matisse's params in your project.

**Comment by teddy0710** [comment]
07-26 14:07:23.820 21903-21903/com.zfl.arms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zfl.arms, PID: 21903
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172)
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
        at android.view.View.performClick(View.java:6367)
        at android.view.View$PerformClick.run(View.java:25032)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhihu.matisse.R$plurals" on path: DexPathList[[zip file "/data/app/com.zfl.arms-NRapbBHYW9VIrFM5Ef5Kaw==/base.apk"],nativeLibraryDirectories=[/data/app/com.zfl.arms-NRapbBHYW9VIrFM5Ef5Kaw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172) 
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71) 
        at android.view.View.performClick(View.java:6367) 
        at android.view.View$PerformClick.run(View.java:25032) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by teddy0710** [comment]
0.5.1-beta1

**Comment by Novice9527** [comment]
有没有解决啊

**Comment by ganzhubing** [comment]
@REBOOTERS 三楼已经提供信息了，什么时候解决啊

**Comment by REBOOTERS** [comment]
@ganzhubing  我按照maxCount = 9 配置后，并没有发生这个问题。不知道是不是因为其他配置项导致的，方便的话提供一下 Matisse 初始化的配置代码吧，方便我进行排查。

**Comment by ganzhubing** [comment]
@REBOOTERS  
Matisse.from(context)
                                    .choose(MimeType.ofImage())
                                    .countable(true)
                                    .maxSelectable(9)
                                    .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
                                    .thumbnailScale(0.85f)
                                    .imageEngine(new GlideEngine())
                                    .forResult(requestCode);

**Comment by REBOOTERS** [comment]
@ganzhubing  👌 ，I will try to resolve this issue as soon as possible.

**Comment by REBOOTERS** [comment]
@ganzhubing  @teddy0710 @Novice9527 

After lots of effort ,I still can't reproduce this bug .

well, I still try to fix this issue and released  0.5.2-beta1, you can try with this version .

I guess that  **R.plurals** resources seems to be unpackaged into apk on some device . which may be related with the project environment . like gradle version, build-tools version ,I'm not sure .

maybe it related with phone language etc .

in issue https://github.com/zhihu/Matisse/issues/416 ,it seems gradle version is key-factor. 

if the bug still unfixed ,please let me know . 

 thank you .

**Comment by ganzhubing** [comment]
@REBOOTERS 还是一样崩溃，我试了好几台手机都一样。
你试试这个gradle版本
classpath 'com.android.tools.build:gradle:3.3.0-alpha02'
distributionUrl=https\://services.gradle.org/distributions/gradle-4.8-all.zip

**Comment by teddy0710** [comment]
感谢 @REBOOTERS，这个问题在我机器上用0.5.2-beta1版本测试已经没有问题。 另外，@ganzhubing 我的版本是gradle-4.9-rc-1-all，com.android.tools.build:gradle:3.3.0-alpha03，一加5,安卓8.1。

**Comment by REBOOTERS** [comment]
Fine ！

**Comment by StuStirling** [comment]
This has been closed but I can't see a resolution. Is the only thing for it to workaround it by specifying the strings ourselves?

**Comment by REBOOTERS** [comment]
with commit https://github.com/zhihu/Matisse/commit/4810de85db7d4a90e9b24e0bce261c5b43036d49 

I didn't reproduce the issue on my devices ,so just add a try catch ,still don't know the real reason.

**Comment by yccheok** [comment]
@REBOOTERS @StuStirling I'm using 0.5.2-beta3. I'm facing the same error too.
