### ISSUE TITLE
sample中mix2s调用相机闪退

### ISSUE THREAD

**Issue by po1arbear** [zhihu/Matisse#449]
Unable to load resource 0x00000000 from pkg=com.android.systemui

**Comment by po1arbear** [comment]
07-26 11:06:23.967 1951-1951/? E/Icon: Unable to load resource 0x00000000 from pkg=com.android.systemui
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:214)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:889)
        at android.content.res.Resources.getDrawable(Resources.java:832)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:323)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:276)
        at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:387)
        at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:195)
        at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:142)
        at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:109)
        at com.android.systemui.statusbar.phone.SimpleStatusBar.updateIcon(SimpleStatusBar.java:278)
        at com.android.systemui.statusbar.phone.PhoneStatusBar.updateIcon(PhoneStatusBar.java:2468)
        at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:455)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6661)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
