### ISSUE TITLE
Unable to resume activity {com.mrhuo.myapp/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by mrhuo** [zhihu/Matisse#455]
选择视频，代码如下：

```
Matisse.from(this)
        .choose(videoMimeTypeSet())
        .countable(false)
        .maxSelectable(1)
        .addFilter(new GalleryVideoFilter())
        .showSingleMediaType(true)
        .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
        .thumbnailScale(0.85f)
        .theme(R.style.Matisse_MrHuo)
        .capture(false)
        .captureStrategy(new CaptureStrategy(false, FILE_PROVIDER_AUTHORATION))
        .imageEngine(new MyPicassoEngine())
        .forResult(MSG_SELECT_VIDEO_CODE);
```

可以打开选择界面，也可以选择视频，但是如果点了预览视频，再打开系统播放器播放视频，播放完按返回键返回后抛出异常。堆栈信息如下：
```
 Process: com.mrhuo.myapp, PID: 28206
 java.lang.RuntimeException: Unable to resume activity {com.mrhuo.myapp/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3220)
     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3251)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:157)
     at android.app.ActivityThread.main(ActivityThread.java:5696)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
  Caused by: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
     at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
     at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
     at android.database.AbstractCursor.moveToNext(AbstractCursor.java:274)
     at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
     at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
     at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
     at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)
     at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:248)
     at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
     at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
     at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
     at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:188)
     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:173)
     at android.support.v4.content.Loader.deliverResult(Loader.java:130)
     at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:107)
     at android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:153)
     at android.support.v4.content.Loader.startLoading(Loader.java:283)
     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:76)
     at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
     at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
     at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
     at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
     at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
     at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
     at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
     at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
     at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
     at android.app.Fragment.performStart(Fragment.java:2244)
     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1002)
     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
     at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1960)
     at android.app.FragmentController.dispatchStart(FragmentController.java:163)
     at android.app.Activity.performStart(Activity.java:6385)
     at android.app.Activity.performRestart(Activity.java:6425)
     at android.app.Activity.performResume(Activity.java:6430)
```

手机系统：小米4，Android 6.0.1，MIUI版本 MIUI 9 （8.4.28），手机已ROOT，无 SIM 卡

**Comment by REBOOTERS** [comment]
Matisse version ?

**Comment by mrhuo** [comment]
implementation 'com.zhihu.android:matisse:0.5.1'

**Comment by REBOOTERS** [comment]
#423

**Comment by mrhuo** [comment]
Thanks
