### ISSUE TITLE
Unable to resume activity {com.it.dathdq.learningkotlin/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by hodangquocdat** [zhihu/Matisse#468]
**Describe the bug**
onResume to AlbumPreviewActivity 

**To Reproduce**
1. Go to 'MatisseActivity through fun Matisse.from(this@HomeFragment)'
2. Click on ' Item review'
3. Click on 'Home device'
4. onResume Application

**Expected behavior**
No crash app and view page AlbumPreviewActivity

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung J7 Pro]
 - OS: [e.g. Android]
 - Version [e.g. 27]

**Additional context**
Process: com.it.dathdq.learningkotlin, PID: 25389
    java.lang.RuntimeException: Unable to resume activity {com.it.dathdq.learningkotlin/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
     Caused by: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
        at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
        at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
        at android.support.v4.content.Loader.deliverResult(Loader.java:132)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:109)
        at android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:155)
        at android.support.v4.content.Loader.startLoading(Loader.java:285)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
        at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
        at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
        at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
        at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
        at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
        at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
        at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
        at android.app.Fragment.performStart(Fragment.java:2378)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2048)
        at android.app.FragmentController.dispatchStart(FragmentController.java:188)
        at android.app.Activity.performStart(Activity.java:6978)
        at android.app.Activity.performRestart(Activity.java:7097)
        at android.app.Activity.performResume(Activity.java:7102)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
        	... 8 more

**Comment by hodangquocdat** [comment]
https://github.com/zhihu/Matisse/issues/423
