### ISSUE TITLE
华为 JDN AL00 报错：android.database.StaleDataException

### ISSUE THREAD

**Issue by chrissen0814** [zhihu/Matisse#481]
**Describe the bug**
java.lang.RuntimeException:Unable to resume activity {com.chrissen.card/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.

**Smartphone (please complete the following information):**
 - Device: [华为 JDN AL00 ， ]
 - OS: [Android 6.0.1,level 23]
 - Version [23]

**Comment by REBOOTERS** [comment]
如何发生的呢？能加点描述吗？

**Comment by chrissen0814** [comment]
我是通过兼容性测试，查看报告时发现有这个错误的，具体的步骤我也不太清楚，抱歉。
这是部分日志信息：
![snipaste_2018-09-14_15-31-43](https://user-images.githubusercontent.com/22590234/45536245-71fc4080-b833-11e8-9164-21f74b191191.png)

**Comment by REBOOTERS** [comment]
不知道你用的是什么版本，Matisse 使用 Loader 来加载内容，本身并没有对 Cursor 做关闭操作，Attempted to access a cursor after it has been closed

这个错误，看起来是不应该发生的。

**Comment by Digitail** [comment]
我也遇到了同样的问题，用的是0.5.1版本。

**Comment by REBOOTERS** [comment]
@Digitail  请尝试新版本，0.5.1 有一个 cursor.close 的误操作。

**Comment by 2292961588** [comment]
0.5.1  上也有这个bug，monkey测试，预览图片经常会崩溃

**Comment by AllenWen** [comment]
同样收集到这个问题，0.5.1版本

**Comment by hugh114** [comment]
和#528是同一个问题。
0.5.1版本，友盟收集到的错误信息，自己没有复现过所以不清楚复现路径
以下是错误信息：

java.lang.RuntimeException: Unable to resume activity {com.chuang.global/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3656)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3696)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1717)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:181)
    at android.app.ActivityThread.main(ActivityThread.java:6431)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
Caused by: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
    at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
    at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
    at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
    at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
    at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.a(AlbumPreviewActivity.java:71)
    at com.chuang.global.xz.a(AlbumMediaCollection.java:64)
    at com.chuang.global.xz.a(AlbumMediaCollection.java:33)
    at android.support.v4.app.LoaderManagerImpl$b.a(LoaderManagerImpl.java:248)
    at android.arch.lifecycle.LiveData.a(LiveData.java:109)
    at android.arch.lifecycle.LiveData.b(LiveData.java:126)
    at android.arch.lifecycle.LiveData.b(LiveData.java:282)
    at android.arch.lifecycle.i.b(MutableLiveData.java:33)
    at android.support.v4.app.LoaderManagerImpl$a.b(LoaderManagerImpl.java:188)
    at android.support.v4.app.LoaderManagerImpl$a.a(LoaderManagerImpl.java:173)
    at android.support.v4.content.e.b(Loader.java:130)
    at android.support.v4.content.d.a(CursorLoader.java:107)
    at android.support.v4.content.d.i(CursorLoader.java:153)
    at android.support.v4.content.e.q(Loader.java:283)
    at android.support.v4.app.LoaderManagerImpl$a.b(LoaderManagerImpl.java:76)
    at android.arch.lifecycle.LiveData$a.a(LiveData.java:410)
    at android.arch.lifecycle.LiveData$LifecycleBoundObserver.a(LiveData.java:368)
    at android.arch.lifecycle.e$a.a(LifecycleRegistry.java:354)
    at android.arch.lifecycle.e.a(LifecycleRegistry.java:292)
    at android.arch.lifecycle.e.d(LifecycleRegistry.java:332)
    at android.arch.lifecycle.e.b(LifecycleRegistry.java:137)
    at android.arch.lifecycle.e.a(LifecycleRegistry.java:123)
    at android.arch.lifecycle.ReportFragment.a(ReportFragment.java:121)
    at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
    at android.app.Fragment.performStart(Fragment.java:2379)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
    at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2044)
    at android.app.FragmentController.dispatchStart(FragmentController.java:187)
    at android.app.Activity.performStart(Activity.java:6883)
    at android.app.Activity.performRestart(Activity.java:6951)
    at android.app.Activity.performResume(Activity.java:6956)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3633)
    ... 8 more
