### ISSUE TITLE
重写getResources()和matisse一起用闪退

### ISSUE THREAD

**Issue by Ajax1995** [zhihu/Matisse#486]
matisse:0.5.2-beta3' 
如果设置最多选择6张图片，当选完6张图片的时候 再点击第7张图片跳到大图然后点击确定的话 会在getResources报空指针

**Comment by REBOOTERS** [comment]
getResources 在哪一行？具体在哪个类？你这问题让我怎么回答？

**Comment by lingdage** [comment]
我也遇到了，必现，当选择max+1张的时候，会弹toast，说最多只能选max张，这时候点确定就崩溃，getResources空指针

**Comment by REBOOTERS** [comment]
https://github.com/zhihu/Matisse/issues/new?template=bug_report.md

提问题的正确方式了解一下 ？？？

@Ajax1995 @lingdage

**Comment by lingdage** [comment]
**Describe the bug**
一个重写过getResources的A activity跳转到matisse，matisse页面如果弹出过“最多只能选择××个文件”这个toast，点确定返回返回A activity，必报空指针。

**To Reproduce**
Steps to reproduce the behavior:
1. A activity 重写getResources
2. A activity跳转到matisse，选择超过最大数后，弹出“最多只能选择××个文件”这个toast（关键，不弹没问题）
3. 确定返回A activity 
4. getResources会报空指针

**Smartphone :**
 - Device: [公司定制手机，杂牌]
 - OS: [android 6.0.1]

**Comment by REBOOTERS** [comment]
你 override getResources 都做了什么呢？ 我简单重写了 demo 里的 SimpleActivity 中这个方法，并没有任何异常

```java
    @Override
    public Resources getResources() {
        Log.e("tag", "override getResources: ");
        return super.getResources();
    }
```

**Comment by REBOOTERS** [comment]
@lingdage

**Comment by lingdage** [comment]
```java
public Resources getResources() {
        Resources res = super.getResources();
        Configuration config = new Configuration();
        config.setToDefaults();
        res.updateConfiguration(config, res.getDisplayMetrics());
        return res;
}
```     

错误：
```  
09-21 13:36:32.026 16966-16966/E/ApplicationCrashHandler: -----------------------2018-09-21 13:36:32 ----------------------------
    Thread: main - 1
    AppVersion: v1.0.180921_r8537_snapshot_d
    DeviceDetail: 
    SUPPORTED_64_BIT_ABIS:  [Ljava.lang.String;@78e5cd3
    versionCode:  1
    BOARD:  msm8976
    BOOTLOADER:  unknown
    TYPE:  user
    ID:  MMB29M
    TIME:  1481093978000
    BRAND:  Kedacom
    TAG:  Build
    SERIAL:  0123456789ABCDEF
    HARDWARE:  qcom
    SUPPORTED_ABIS:  [Ljava.lang.String;@6180010
    CPU_ABI:  armeabi-v7a
    RADIO:  unknown
    IS_DEBUGGABLE:  false
    MANUFACTURER:  
    SUPPORTED_32_BIT_ABIS:  [Ljava.lang.String;@552f6c2
    TAGS:  release-keys
    CPU_ABI2:  armeabi
    UNKNOWN:  unknown
    USER:  sysbuild
    FINGERPRINT:  /p1s:6.0.1/MMB29M/P1S_Dual-V0.31:user/release-keys
    HOST:  sysbuild-PC
    PRODUCT:  p1s
    versionName:  v1.0.180921_r8537_snapshot_d
    DISPLAY:  P1S_Dual-V0.31
    MODEL:  P1S
    DEVICE:  p1s
    ErrorInfo: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Locale.toString()' on a null object reference
        at libcore.icu.NativePluralRules.forLocale(NativePluralRules.java:50)
        at android.content.res.Resources.updateConfiguration(Resources.java:2062)
        at android.content.res.Resources.updateConfiguration(Resources.java:1970)
        at com.uc.common.resource.activity.ModuleSupportActivity.getResources(ModuleSupportActivity.java:81)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1407)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6016)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:606)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by REBOOTERS** [comment]
- 用同样写法没有复现问题 （Android 8.0 小米 5) 
- updateConfiguration(config, res.getDisplayMetrics())  是一个已经废弃的方法，不知道是不是和兼容性有关
- **从你提供的 crash log 来开，这个 npe  发生的地结点和 Matisse 没有关系，建议去 stackoverflow 上看看**

**Comment by 736870598** [comment]
我也遇到这个问题，感觉是在在android新版本上没有出现，但是在android、6.0版本上出现了，错误日志：
java.io.IOException: Invalid marker: 89
        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1627)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1353)
        at android.media.ExifInterface.<init>(ExifInterface.java:1070)
        at com.zhihu.matisse.internal.utils.ExifInterfaceCompat.newInstance(ExifInterfaceCompat.java:54)
        at com.zhihu.matisse.internal.utils.PhotoMetadataUtils.shouldRotate(PhotoMetadataUtils.java:160)
        at com.zhihu.matisse.internal.utils.PhotoMetadataUtils.getBitmapSize(PhotoMetadataUtils.java:64)
        at com.zhihu.matisse.internal.ui.PreviewItemFragment.onViewCreated(PreviewItemFragment.java:97)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:94)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
        at android.support.v4.content.Loader.deliverResult(Loader.java:126)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
        at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
        at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
        at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
