### ISSUE TITLE
Binary XML file line #31: Error inflating class TextView

### ISSUE THREAD

**Issue by YooTrepeat** [zhihu/Matisse#524]
**Describe the bug**
id: selected_album this textview crash

**Screenshots**
Caused by android.view.InflateException: Binary XML file line #31: Error inflating class TextView
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:809)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java)
       at android.app.Activity.performCreate(Activity.java:6372)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
       at android.app.ActivityThread.access$900(ActivityThread.java:168)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5665)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

**Smartphone (please complete the following information):**
 - Device: [HUAWEI]
 - OS: [Android 6]
 - Version [com.zhihu.android:matisse:0.4.3]

**Comment by waqarv712** [comment]
Same Issue....

**Comment by Merbn** [comment]
me too

**Comment by hardyio** [comment]
me too

**Comment by liguanyang** [comment]
me too

**Comment by Hunter2916** [comment]
me too
