### ISSUE TITLE
android.database.StaleDataException: Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by 505541778** [zhihu/Matisse#528]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

1 java.lang.RuntimeException:Unable to resume activity {com.akaxin.zaly/com.zhihu.matisse.internal.ui.AlbumPreviewActivity}: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
--
2 android.app.ActivityThread.performResumeActivity(ActivityThread.java:3711)
3 ......
4 Caused by:
5 android.database.StaleDataException:Attempted to access a cursor after it has been closed.
6 android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
7 android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
8 android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
9 android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
10 android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
11 com.zhihu.matisse.internal.ui.AlbumPreviewActivity.a(AlbumPreviewActivity.java:71)
12 com.zhihu.matisse.internal.b.b.a(AlbumMediaCollection.java:64)
13 com.zhihu.matisse.internal.b.b.onLoadFinished(AlbumMediaCollection.java:33)
14 android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:248)
15 android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
16 android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
17 android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
18 android.arch.lifecycle.i.setValue(MutableLiveData.java:33)
19 android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:188)
20 android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:173)
21 android.support.v4.content.Loader.deliverResult(Loader.java:130)
22 android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:107)
23 android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:153)
24 android.support.v4.content.Loader.startLoading(Loader.java:283)
25 android.support.v4.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:76)
26 android.arch.lifecycle.LiveData$b.a(LiveData.java:410)
27 android.arch.lifecycle.LiveData$LifecycleBoundObserver.a(LiveData.java:368)
28 android.arch.lifecycle.e$a.a(LifecycleRegistry.java:354)
29 android.arch.lifecycle.e.a(LifecycleRegistry.java:292)
30 android.arch.lifecycle.e.d(LifecycleRegistry.java:332)
31 android.arch.lifecycle.e.b(LifecycleRegistry.java:137)
32 android.arch.lifecycle.e.a(LifecycleRegistry.java:123)
33 android.arch.lifecycle.l.a(ReportFragment.java:121)
34 android.arch.lifecycle.l.onStart(ReportFragment.java:81)
35 android.app.Fragment.performStart(Fragment.java:2637)
36 android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1312)
37 android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
38 android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
39 android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3039)
40 android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2996)
41 android.app.FragmentController.dispatchStart(FragmentController.java:189)
42 android.app.Activity.performStart(Activity.java:6998)
43 android.app.Activity.performRestart(Activity.java:7066)
44 android.app.Activity.performResume(Activity.java:7071)
45 android.app.ActivityThread.performResumeActivity(ActivityThread.java:3686)
46 android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3751)
47 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
48 android.os.Handler.dispatchMessage(Handler.java:105)
49 android.os.Looper.loop(Looper.java:164)
50 android.app.ActivityThread.main(ActivityThread.java:6653)
51 java.lang.reflect.Method.invoke(Native Method)
52 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
53 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by QiLiKing** [comment]
I got this exception from monkey:

 Caused by: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
        at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
        at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:248)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:188)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:173)
        at android.support.v4.content.Loader.deliverResult(Loader.java:130)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:107)
        at android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:153)
        at android.support.v4.content.Loader.startLoading(Loader.java:283)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:76)
        at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
        at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
        at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
        at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
        at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
        at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
        at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
        at android.app.Fragment.performStart(Fragment.java:2305)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1018)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1980)
        at android.app.FragmentController.dispatchStart(FragmentController.java:164)
        at android.app.Activity.performStart(Activity.java:6954)
        at android.app.Activity.performRestart(Activity.java:7002)
        at android.app.Activity.performResume(Activity.java:7007)

**Comment by 505541778** [comment]
check一下  是matisse的问题吗

**Comment by sendtion** [comment]
我也遇到了问题

**Comment by githubyxl** [comment]
这个问题有得到解决吗

**Comment by sendtion** [comment]
@githubyxl 最新版本解决了，0.5.2-beta4

**Comment by QiLiKing** [comment]
ok♥
  
  
  

  
  
  
  
  
>

**Comment by AllenWen** [comment]
0.5.2-beta4，仍然收集到这个异常
