### ISSUE TITLE
Error when trying to get the camera result

### ISSUE THREAD

**Issue by bruferrari** [zhihu/Matisse#542]
Hi, I'm getting this error trying to get the image from the library camera button:
```
2018-11-21 15:51:53.179 4550-4550/? E/CAM_StateSavePic: exception while saving result to URI: Optional.of(content://br.com.kroton.gnaction/my_images/foca_captures/JPEG_20181121_155150.jpg)
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:625)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1265)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1007)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:983)
        at com.android.camera.captureintent.state.StateSavingPicture.onEnter(StateSavingPicture.java:84)
        at com.android.camera.captureintent.stateful.StateMachineImpl.jumpToState(StateMachineImpl.java:62)
        at com.android.camera.captureintent.stateful.StateMachineImpl.processEvent(StateMachineImpl.java:110)
        at com.android.camera.captureintent.state.StateOpeningCamera$9.onClick(StateOpeningCamera.java:307)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
The sample app works just fine but I can't find why this is happening on my app.

**Comment by fedyiv** [comment]
@bruferrari have you been able to solve this issue? I have the same one

UPDATED: I have found the solution. The issue seems to be specific to Android 10 and fixed in Android 11.
Solution is to add fololowing code to manifest
```
<application...
            android:requestLegacyExternalStorage="true"
```
