### ISSUE TITLE
R.plurals.error_over_count这个资源国际化的values没有定义报错Failed resolution of: Lcom/zhihu/matisse/R$plurals

### ISSUE THREAD

**Issue by ttttupup** [zhihu/Matisse#555]
0.5.1版本，设置图片数量，maxSelectable（）。如果大于了再点击，会提示，以前版本用的是好的，现在报错了。Failed resolution of: Lcom/zhihu/matisse/R$plurals。发现SelectedItemCollection.isAcceptable（）方法调用了，R.plurals.error_over_count，但是values-zh.xml里是没有加入这个，再issues里看到别人发的资源文件里有。

**Comment by ttttupup** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
                      at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
                      at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
                      at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172)
                      at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)


安卓8.1.看了最新版本，好像也没有加进去。

**Comment by ttttupup** [comment]
只能自己加个咯， 
 <plurals name="error_over_count">
        <item quantity="one">最多只能选择 %1$d 个文件</item>
        <item quantity="many">最多只能选择 %1$d 个文件</item>
    </plurals>

**Comment by ttttupup** [comment]
`  <plurals name="error_over_count">
        <item quantity="one">最多只能选择 %1$d 个文件</item>
        <item quantity="many">最多只能选择 %1$d 个文件</item>
    </plurals>`

**Comment by ttttupup** [comment]
只能自己加个了`  <plurals name="error_over_count">
        <item quantity="one">最多只能选择 %1$d 个文件</item>
        <item quantity="many">最多只能选择 %1$d 个文件</item>
    </plurals>`

**Comment by OneGreenHand** [comment]
@ttttupup 0.5.2-bata已经有了
