### ISSUE TITLE
Crash while pick image with camera

### ISSUE THREAD

**Issue by pranavlathigara** [zhihu/Matisse#593]
First of all this is great library for image picking
but i am facing some issue while capture image from camera my error log is given below
Note : This lib perfectly work with local image pick but issue with camera result 

` Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
        at com.zhihu.matisse.internal.utils.PathUtils.getDataColumn(PathUtils.java:101)
        at com.zhihu.matisse.internal.utils.PathUtils.getPath(PathUtils.java:71)
        at com.dabbel.activity.UpdateProfileActivity.onActivityResult(Activity.kt:261)
        at android.app.Activity.dispatchActivityResult(Activity.java:7305)`

**Comment by remylavergne** [comment]
Same here for the last beta5. Any update ?

**Comment by REBOOTERS** [comment]
device ? Android Os ? @pranavlathigara

**Comment by pranavlathigara** [comment]
Device : Motorola G5
OS : Oreo (8.1)
