### ISSUE TITLE
crash when choosing picture

### ISSUE THREAD

**Issue by veargithub** [zhihu/Matisse#595]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

Process: com.vart.zdian, PID: 29207
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:185)
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhihu.matisse.R$plurals" on path: DexPathList[[zip file "/data/app/com.vart.zdian-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vart.zdian-1/lib/arm64, /data/app/com.vart.zdian-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:185) 
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71) 
        at android.view.View.performClick(View.java:5198) 
        at android.view.View$PerformClick.run(View.java:21147) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: com.zhihu.matisse.R$plurals
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

any body help?

i select one picture,  when  i select another one, the app crashes

**Comment by liangxiwei** [comment]
this is an Android project...why your iphone can install it??

**Comment by veargithub** [comment]
the text above is default template, i install it with nexus 6

**Comment by liangxiwei** [comment]
the newest code already fix the crash. But the version not publish it.

maybe you need to fork and download the code..build a module and reference your module

**Comment by veargithub** [comment]
is it supports androidx?
