### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Class 'com.zhihu.matisse.ui.MatisseActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.

### ISSUE THREAD

**Issue by WongChoBun** [zhihu/Matisse#622]
**Describe the bug**
打开Matisse选择图片出现崩溃

**Expected behavior**

**Screenshots**
    java.lang.IncompatibleClassChangeError: Class 'com.zhihu.matisse.ui.MatisseActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.nc.hubble_dev-OFfzUVept_7xkcnhVaiGbw==/split_lib_dependencies_apk.apk)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:421)
        at com.zhihu.matisse.internal.model.AlbumCollection.loadAlbums(AlbumCollection.java:98)
        at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:152)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Smartphone (please complete the following information):**
 - Device: [荣耀9]
 - OS: [Android8.0]
 - Version [0.5.2-beta4]

**Additional context**

**Comment by REBOOTERS** [comment]
https://github.com/zhihu/Matisse/issues/631

**Comment by xuhuajie0** [comment]
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.annotation:annotation:1.1.0'
    annotationProcessor 'androidx.annotation:annotation:1.1.0'
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

更新Androidx到最新版本，解决这个问题
