### ISSUE TITLE
【已解决】无法正常使用，一点击就崩溃  java.lang.IncompatibleClassChangeError: Class 'com.zhihu.matisse.ui.MatisseActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner'

### ISSUE THREAD

**Issue by xuhuajie0** [zhihu/Matisse#631]
java.lang.IncompatibleClassChangeError: Class 'com.zhihu.matisse.ui.MatisseActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.whalevii.m77-n_PvxFQuVBaC4duefCd4sQ==/split_lib_dependencies_apk.apk)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:421)
        at com.zhihu.matisse.internal.model.AlbumCollection.loadAlbums(AlbumCollection.java:98)
        at com.zhihu.matisse.ui.MatisseActivity.onCreate(MatisseActivity.java:152)
        at android.app.Activity.performCreate(Activity.java:7084)
        at android.app.Activity.performCreate(Activity.java:7075)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:38)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
2019-07-16 21:25:29.667 26559-26559/com.whalevii.m77 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
2019-07-16 21:25:29.670 26559-26559/com.whalevii.m77 D/CrashReport: [Database] deleted t_lr data 1
2019-07-16 21:25:29.675 26559-26559/com.whalevii.m77 D/CrashReport: [Database] insert t_lr success.
2019-07-16 21:25:29.675 26559-26559/com.whalevii.m77 I/CrashReportInfo: [crash] a crash occur, handling...
2019-07-16 21:25:29.684 26559-26559/com.whalevii.m77 D/CrashReport: [Database] insert t_cr success.
2019-07-16 21:25:29.685 26559-26559/com.whalevii.m77 D/CrashReport: insert t_cr success!
2019-07-16 21:25:29.685 26559-26559/com.whalevii.m77 I/CrashReportInfo: [crash] save crash success
2019-07-16 21:25:29.685 26559-26559/com.whalevii.m77 I/CrashReport: try to upload right now
2019-07-16 21:25:29.686 26559-26559/com.whalevii.m77 D/CrashReport: attach pageTracingList
2019-07-16 21:25:29.688 26559-26559/com.whalevii.m77 D/CrashReport: java.lang.IncompatibleClassChangeError rid:7577b4d8-ecd8-44f3-88ae-54848a2742a8 sess:7e5bc073-ac47-4f13-b771-dc19c000b02c ls:56s isR:false isF:false isM:false isN:false mc:0 ,null ,isUp:false ,vm:33
2019-07-16 21:25:29.695 26559-26559/com.whalevii.m77 W/om.whalevii.m77: type=1400 audit(0.0:122138): avc: denied { read } for name="type" dev="sysfs" ino=38562 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
2019-07-16 21:25:29.701 26559-26559/com.whalevii.m77 D/CrashReport: [UploadMana

**Comment by REBOOTERS** [comment]
try with 0.5.2-beta5

**Comment by REBOOTERS** [comment]
https://github.com/firebase/FirebaseUI-Android/issues/1544

it seems caused by **androidx.core:core**  library .

force the version to 1.0.2 ( androidx.fragment:fragment:1.0.0 transitive it to androidx.core:core:1.1.0-rc1 .

`configurations.all {
    resolutionStrategy.force 'androidx.core:core:1.0.2'
}` 

just have a try

**Comment by xuhuajie0** [comment]
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.annotation:annotation:1.1.0'
    annotationProcessor 'androidx.annotation:annotation:1.1.0'
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

更新Androidx到最新版本，解决这个问题
