### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Allyns** [zhihu/Matisse#632]
2019-07-18 10:49:54.135 21290-21290/com.witstec.sz.wiseeslbht E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.witstec.sz.wiseeslbht, PID: 21290
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhihu/matisse/R$plurals;
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172)
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
        at android.view.View.performClick(View.java:6663)
        at android.view.View.performClickInternal(View.java:6635)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26199)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhihu.matisse.R$plurals" on path: DexPathList[[zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/base.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_dependencies_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_resources_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_0_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_1_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_2_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_3_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_4_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_5_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_6_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_7_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_8_apk.apk", zip file "/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.zhihu.matisse.internal.model.SelectedItemCollection.isAcceptable(SelectedItemCollection.java:175) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.assertAddSelection(AlbumMediaAdapter.java:206) 
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onCheckViewClicked(AlbumMediaAdapter.java:172) 
        at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71) 
        at android.view.View.performClick(View.java:6663) 
        at android.view.View.performClickInternal(View.java:6635) 
        at android.view.View.access$3100(View.java:794) 
        at android.view.View$PerformClick.run(View.java:26199) 
        at android.os.Handler.handleCallback(Handler.java:907) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7593) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.witstec.sz.wiseeslbht-4TpcvcVzddpsqoCUBw852w==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:84)
2019-07-18 10:49:54.135 21290-21290/com.witstec.sz.wiseeslbht E/AndroidRuntime:     at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:801)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:884)
        at android.app.LoadedApk.getResources(LoadedApk.java:1135)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2623)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6568)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2011)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        		... 5 more

**Comment by REBOOTERS** [comment]
https://github.com/zhihu/Matisse/issues/446#issuecomment-408839368
