### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Rodriquetoby** [zhihu/Matisse#641]
08-12 09:58:45.140 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: TimeStamps from Cache: lucid = 20081231190000, customer = 20081231190000
08-12 09:58:45.140 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Cache valid RC: lucid = 2, customer = 2
08-12 09:58:45.142 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Priority black list: 0
08-12 09:58:45.142 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Mode = WVS
08-12 09:58:45.142 30393-30439/com.example.hpi5.e_contact E/libPowerStretch:  STATICS !!! m_enableIce = 1 , s_IceEnabledFirst = 0
08-12 09:58:45.144 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Ice is working with black list method
08-12 09:58:45.154 30393-30439/com.example.hpi5.e_contact E/libc: Access denied finding property "ro.sf.lcd_density"
08-12 09:58:45.158 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: HI from Dynamix Resolution: lucid_dr , mEnabled = 1
08-12 09:58:45.160 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: EglCreateWindowSurfaceImp pid 30393 != tid 30439  mResized = 1 [720 1404] 1.000000 mIsIceDelayed_wl 1  mIsIceMainThread 0 m_HardCodedBlackListed 1 _X_
08-12 09:58:45.363 30393-30439/com.example.hpi5.e_contact E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
08-12 09:58:45.375 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: TimeStamps from Cache: lucid = 20081231190000, customer = 20081231190000
08-12 09:58:45.375 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Cache valid RC: lucid = 2, customer = 2
08-12 09:58:45.376 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Priority black list: 0
08-12 09:58:45.376 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Mode = WVS
08-12 09:58:45.378 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Ice is working with black list method
08-12 09:58:45.386 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: EglCreateWindowSurfaceImp pid 30393 != tid 30439  mResized = 1 [720 1404] 1.000000 mIsIceDelayed_wl 1  mIsIceMainThread 0 m_HardCodedBlackListed 1 _X_
08-12 09:58:46.151 30393-30439/com.example.hpi5.e_contact E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
08-12 09:58:46.156 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: TimeStamps from Cache: lucid = 20081231190000, customer = 20081231190000
08-12 09:58:46.156 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Cache valid RC: lucid = 2, customer = 2
08-12 09:58:46.158 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Priority black list: 0
08-12 09:58:46.158 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Mode = WVS
08-12 09:58:46.160 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Ice is working with black list method
08-12 09:58:46.169 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: EglCreateWindowSurfaceImp pid 30393 != tid 30439  mResized = 1 [720 1500] 1.000000 mIsIceDelayed_wl 1  mIsIceMainThread 0 m_HardCodedBlackListed 1 _X_
08-12 09:58:48.138 30393-30439/com.example.hpi5.e_contact E/[EGL-ERROR]: __egl_platform_cancel_buffers:644: surface->num_buffers(4)
08-12 09:58:48.142 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: TimeStamps from Cache: lucid = 20081231190000, customer = 20081231190000
08-12 09:58:48.142 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Cache valid RC: lucid = 2, customer = 2
08-12 09:58:48.144 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Priority black list: 0
08-12 09:58:48.144 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Mode = WVS
08-12 09:58:48.146 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: Ice is working with black list method
08-12 09:58:48.149 30393-30439/com.example.hpi5.e_contact E/libPowerStretch: EglCreateWindowSurfaceImp pid 30393 != tid 30439  mResized = 1 [720 1404] 1.000000 mIsIceDelayed_wl 1  mIsIceMainThread 0 m_HardCodedBlackListed 1 _X_
08-12 09:58:53.470 30393-30393/com.example.hpi5.e_contact E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.hpi5.e_contact, PID: 30393
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.hpi5.e_contact/com.example.hpi5.e_contact.Maps}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.MapFragment.getMapAsync(com.google.android.gms.maps.OnMapReadyCallback)' on a null object reference
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2884)
                                                                                at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.MapFragment.getMapAsync(com.google.android.gms.maps.OnMapReadyCallback)' on a null object reference
                                                                                at com.example.hpi5.e_contact.Maps.onCreate(Maps.java:165)
                                                                                at android.app.Activity.performCreate(Activity.java:7044)
                                                                                at android.app.Activity.performCreate(Activity.java:7035)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2759)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2884) 
                                                                                at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                at android.os.Looper.loop(Looper.java:164) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6524) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by REBOOTERS** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.maps.MapFragment.getMapAsync(com.google.android.gms.maps.OnMapReadyCallback)' on a null object reference
