### ISSUE TITLE
StrictMode

### ISSUE THREAD

**Issue by blackberry2016** [zhihu/Matisse#657]
开启StrictMode，点击照相
```
at com.zhihu.matisse.internal.utils.MediaStoreCompat.createImageFile(MediaStoreCompat.java:118)
        at com.zhihu.matisse.internal.utils.MediaStoreCompat.dispatchCaptureIntent(MediaStoreCompat.java:79)
        at com.zhihu.matisse.ui.MatisseActivity.capture(MatisseActivity.java:424)
        at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter$1.onClick(AlbumMediaAdapter.java:75)
```

**Comment by REBOOTERS** [comment]
有完整日志吗？？？？🤔
