### ISSUE TITLE
升级到 Android 10,后调用Matisse崩溃 : Invalid column COUNT(*) AS count

### ISSUE THREAD

**Issue by JakePrim** [zhihu/Matisse#659]
**Describe the bug**
升级到 Android 10,后调用Matisse崩溃 
 Invalid column COUNT(*) AS count
**To Reproduce**
` Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:114)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) `
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9129414/64229704-1aac2000-cf1d-11e9-84b4-100d0b1e84d4.png)
**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3 XL]
 - OS: [e.g. Android 29]
 - Version [29]

**Comment by REBOOTERS** [comment]
还没有适配 Android 10 ，近期会支持一下。

**Comment by william198824** [comment]
我也遇到了

**Comment by yccheok** [comment]
Just an additional note to all, if you intent to reproduce this problem in Android Q, which introduces scoped storage recently, you need to change Matisse library and Matisse sample's `build.gradle`, to both

`compileSdkVersion 29` and `targetSdkVersion 29`

**Comment by yccheok** [comment]
同志好！

我尝试修复 Android Q 的臭虫。因为我对 ``CursorLoader` 并不了解。如果你能找出更好的方案，请修正。

谢谢同志们！

https://github.com/zhihu/Matisse/pull/665/commits/2c8f6f8647a1e7503dffa62bce2a59eaccd6e872

**Comment by yccheok** [comment]
因为 `MediaStore.MediaColumns.DATA` 已经 deprecated ，我建议把 `Album` 的 `mCoverPath` 转换成 `mCoverUri` 
 - https://github.com/zhihu/Matisse/pull/665/commits/4cccb27fef84963643f1a261fb71f33512f823b7

我比较不确定的是，会不会在一些刁钻的状况，`Uri.toString` / `Uri.parse` 的相互转换会失败？

**Comment by JocelynDavid** [comment]
I got the same crash on version 0.5.3-beta2, any idea when a fix will be added to the library?

**Comment by REBOOTERS** [comment]
近期工作中的事情比较多，会抽空进行适配。

**Comment by Jocerly** [comment]
可以暂时按照 issues 646 来改

**Comment by kilo-swodh** [comment]
希望尽快适配Android 10

**Comment by REBOOTERS** [comment]
> 希望尽快适配Android 10

https://github.com/zhihu/Matisse/releases/tag/v0.5.3-beta3 已经适配了呀。

**Comment by kilo-swodh** [comment]
> > 希望尽快适配Android 10
> 
> https://github.com/zhihu/Matisse/releases/tag/v0.5.3-beta3 已经适配了呀。

抱歉,已发现是我这边没适配好Android 10的外部存储限制

**Comment by wlong800** [comment]
api 'com.zhihu.android:matisse:0.5.3-beta3'
为啥编译不过


ERROR: Unable to resolve dependency for ':PhotoSdk@debug/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: PhotoSdk


ERROR: Unable to resolve dependency for ':PhotoSdk@debugAndroidTest/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: PhotoSdk


ERROR: Unable to resolve dependency for ':PhotoSdk@debugUnitTest/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: PhotoSdk


ERROR: Unable to resolve dependency for ':PhotoSdk@release/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: PhotoSdk


ERROR: Unable to resolve dependency for ':PhotoSdk@releaseUnitTest/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: PhotoSdk


ERROR: Unable to resolve dependency for ':App@debug/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: App


ERROR: Unable to resolve dependency for ':App@debugAndroidTest/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: App


ERROR: Unable to resolve dependency for ':App@debugUnitTest/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: App


ERROR: Unable to resolve dependency for ':App@release/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: App


ERROR: Unable to resolve dependency for ':App@releaseUnitTest/compileClasspath': Could not download matisse.aar (com.zhihu.android:matisse:0.5.3-beta3)
Show Details
Affected Modules: App

**Comment by wlong800** [comment]
@JakePrim kilo-swodh

**Comment by yozo2020** [comment]
> > 希望尽快适配Android 10
> 
> https://github.com/zhihu/Matisse/releases/tag/v0.5.3-beta3 已经适配了呀。

提交的文件一个更改gradle的库，一个增加了string文件，没见到实质性的适配10

**Comment by serreau** [comment]
Same problem with Android 10 (pixel 4)

2020-03-26 20:32:13.820 1815-2067/*** E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: sero.com.microcosmos, PID: 1815
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by serreau** [comment]
Same problem with Android 10 (pixel 4)

2020-03-26 20:32:13.820 1815-2067/[my project name] E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: [my project name] , PID: 1815
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by baizhu0414** [comment]
我遇到了类似的问题：（已经调整编译环境到buildVersion29）
2021-05-06 19:33:13.231 5150-5239/com.example.testmatisse E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.example.testmatisse, PID: 5150
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:946)
        at android.content.ContentResolver.query(ContentResolver.java:881)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 


`compileSdkVersion 29`
    `defaultConfig {
        applicationId 'com.example.testmatisse'
        minSdkVersion 14
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
    }`

另外，我运行Demo时没有出问题，但是我已经基本保持和Demo一致的环境了，唯一不同就是依赖方式了。

**Comment by baizhu0414** [comment]
> 我遇到了类似的问题：（已经调整编译环境到buildVersion29）
> 2021-05-06 19:33:13.231 5150-5239/com.example.testmatisse E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
> Process: com.example.testmatisse, PID: 5150
> java.lang.RuntimeException: An error occurred while executing doInBackground()
> at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
> at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)
> Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
> at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
> at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
> at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
> at android.content.ContentResolver.query(ContentResolver.java:946)
> at android.content.ContentResolver.query(ContentResolver.java:881)
> at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
> at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
> at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
> at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
> at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
> at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
> at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
> at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
> at java.lang.Thread.run(Thread.java:919) 
> 
> `compileSdkVersion 29`
> `defaultConfig { applicationId 'com.example.testmatisse' minSdkVersion 14 targetSdkVersion 29 versionCode 1 versionName "1.0" }`
> 
> 另外，我运行Demo时没有出问题，但是我已经基本保持和Demo一致的环境了，唯一不同就是依赖方式了。

抱歉，我修改到0.5.3-beta后此问题解决。请问为什么没有0.5.3正式版呢？是问题没有彻底解决吗？

**Comment by DanteAndroid** [comment]
有临时解决方案吗？项目用的是源码依赖的方式，没法直接升级……
