### ISSUE TITLE
预览图片黑屏，Glide提示 java.io.FileNotFoundException

### ISSUE THREAD

**Issue by Vander-liu** [zhihu/Matisse#666]
我查阅源码后发现 预览的时候，Matisse使用uri去加载图片。但是Android7.0以后貌似Uri访问存在权限问题。

在Demo上也会出现这个问题。

**Comment by Vander-liu** [comment]
java.io.FileNotFoundException: No such file or directory
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1181)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1000)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:923)
        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:22)
        at com.bumptech.glide.load.data.AssetFileDescriptorLocalUriFetcher.loadResource(AssetFileDescriptorLocalUriFetcher.java:13)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:397)
        at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:119)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherFailed(DecodeJob.java:397)
        at com.bumptech.glide.load.engine.SourceGenerator.onLoadFailed(SourceGenerator.java:119)
        at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:49)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)

**Comment by Vander-liu** [comment]
com.zhihu.matisse.sample E/PhotoMetadataUtils: could not read exif info of the image: content://media/external/images/media/6840

**Comment by Vander-liu** [comment]
@REBOOTERS

**Comment by REBOOTERS** [comment]
你用的图片什么格式的？

**Comment by Vander-liu** [comment]
@REBOOTERS  找到原因了。我去图库去看下照片格式，发现这些照片 都是color.png ，然后无法展示，并且点击提示图库不存在。

我这美图手机 前两天刚升级 我估计7.0 -》 7.1.1 然后图库产生了问题。

感谢~

@REBOOTERS

**Comment by BigBigDeBoy** [comment]
@Vander-liu 解决了吗 我也遇到这个问题 华为P30 android10
