### ISSUE TITLE
可以尽快适配一下Android 10 吗？谢谢

### ISSUE THREAD

**Issue by RealFeeling** [zhihu/Matisse#685]
Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.chan.cwallpaper.widget.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:120)
        at com.chan.cwallpaper.widget.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:36)

**Comment by REBOOTERS** [comment]
https://github.com/zhihu/Matisse/issues/659  

duplicate
