### ISSUE TITLE
报错了，可能是因为album_element_color 找不到导致的

### ISSUE THREAD

**Issue by zhuoshirong** [zhihu/Matisse#686]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhihu.matisse.ui.MatisseActivity}: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class TextView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:163)
    at android.app.ActivityThread.main(ActivityThread.java:6358)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
Caused by: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class TextView
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f04002f a=-1}
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
    at android.widget.TextView.<init>(TextView.java:1076)
    at android.widget.TextView.<init>(TextView.java:704)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
    at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
    at com.zhihu.matisse.ui.MatisseActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:6840)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:163)
    at android.app.ActivityThread.main(ActivityThread.java:6358)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class TextView
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f04002f a=-1}
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
    at android.widget.TextView.<init>(TextView.java:1076)
    at android.widget.TextView.<init>(TextView.java:704)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
    at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
    at com.zhihu.matisse.ui.MatisseActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:6840)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:163)
    at android.app.ActivityThread.main(ActivityThread.java:6358)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
android.view.InflateException: Binary XML file line #32: Error inflating class TextView
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f04002f a=-1}
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
    at android.widget.TextView.<init>(TextView.java:1076)
    at android.widget.TextView.<init>(TextView.java:704)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
    at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
    at com.zhihu.matisse.ui.MatisseActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:6840)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:163)
    at android.app.ActivityThread.main(ActivityThread.java:6358)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f04002f a=-1}
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:530)
    at android.widget.TextView.<init>(TextView.java:1076)
    at android.widget.TextView.<init>(TextView.java:704)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java)
    at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java)
    at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
    at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
    at com.zhihu.matisse.ui.MatisseActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:6840)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:163)
    at android.app.ActivityThread.main(ActivityThread.java:6358)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)

**Comment by REBOOTERS** [comment]
https://github.com/zhihu/Matisse/issues/377

是最新版本吗？
