### ISSUE TITLE
预览视频并播放，此时返回上一个界面崩溃

### ISSUE THREAD

**Issue by 2314372037** [zhihu/Matisse#716]
AlbumPreviewActivity的onAlbumMediaLoad方法报错
Cursor被关闭，但是还尝试cursor.moveToNext()
版本：0.5.1（新版本貌似还是没修复）

日志:
android.database.StaleDataException: Attempted to access a cursor after it has been closed.
        at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
        at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
        at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
        at com.zhihu.matisse.internal.ui.AlbumPreviewActivity.onAlbumMediaLoad(AlbumPreviewActivity.java:71)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:64)
        at com.zhihu.matisse.internal.model.AlbumMediaCollection.onLoadFinished(AlbumMediaCollection.java:33)

**Comment by xeemoo** [comment]
https://github.com/zhihu/Matisse/commit/41f61c6bb43eb7d86cfa51b531647bd5fb2fa2cd
