### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;

### ISSUE THREAD

**Issue by giolaoit** [zhihu/Matisse#74]
I have an issue when use lib.
An error occurred with log:
`                                                                      Process: net.awpspace.cutecrop, PID: 26234
                                                                       java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
                                                                           at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:35)
                                                                           at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                           at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                           at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                           at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                           at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                           at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
                                                                           at android.view.View.layout(View.java:16001)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5181)
                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
                                                                       	at android.view.ViewRootImpl.performTra`
How to resolve this? thanks!

**Comment by gejiaheng** [comment]
@giolaoit Are you using Glide?

**Comment by giolaoit** [comment]
I don't use Glide lib.
I added compile 'com.github.bumptech.glide:glide:3.7.0' to buld.grade then don't see this bug.

**Comment by gejiaheng** [comment]
Please refer to **Proguard** in README, I think it may be caused by proguard rules.
