### ISSUE TITLE
Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by Roy419** [zhihu/Matisse#757]
依赖 com.zhihu.android:matisse:0.5.0
Fatal Exception: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
       at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
       at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
       at android.database.CursorWrapper.getCount(CursorWrapper.java:60)
       at android.database.MergeCursor.getCount(MergeCursor.java:61)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at com.zhihu.matisse.ui.MatisseActivity$1.run(MatisseActivity.java:370)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by xingstarx** [comment]
同样碰到这个问题，希望给点意见

**Comment by 494293346** [comment]
+1
