### ISSUE TITLE
Android 10直接Crash，Matisse版本 0.5.2

### ISSUE THREAD

**Issue by ZengCS** [zhihu/Matisse#768]
Android 10直接Crash，Matisse版本 0.5.2

**Comment by summerhotready** [comment]
我也遇到这个问题了

**Comment by summerhotready** [comment]
我也遇到这个问题了
![image](https://user-images.githubusercontent.com/12251049/81252241-05f9cc00-9058-11ea-894f-1f8586810ea0.png)

#102 java.lang.IllegalArgumentException
Invalid column COUNT(*) AS count

com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)

**Comment by Im-Mark42** [comment]
i am also getting the same error @ZengCS @summerhotready

**Comment by summerhotready** [comment]
将版本更新到0.5.3-beta3后Android10不会发生崩溃，但红米上拍照不能返回照片数据，而是停留在选图页面。查询相册后也未查到任何照片，不建议使用拍照功能
相机设置如下
 .capture(true) // 使用相机，和 captureStrategy 一起使用
 .captureStrategy( CaptureStrategy(true, String.format("%s.fileprovider", getPackageName())))

**Comment by azizarc88** [comment]
me to, have this issue
```
Caused by java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:423)
       at android.content.ContentResolver.query(ContentResolver.java:963)
       at android.content.ContentResolver.query(ContentResolver.java:898)
       at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
       at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
       at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
       at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
       at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
       at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
       at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
       at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by yccheok** [comment]
> 将版本更新到0.5.3-beta3后Android10不会发生崩溃，但红米上拍照不能返回照片数据，而是停留在选图页面。查询相册后也未查到任何照片，不建议使用拍照功能
> 相机设置如下
> .capture(true) // 使用相机，和 captureStrategy 一起使用
> .captureStrategy( CaptureStrategy(true, String.format("%s.fileprovider", getPackageName())))

你好。我之前做了些 Android Q 修复。可，我并没做大量测试。

这问题只发生在特定机型吗？其他的机型呢？

在 Android 9 或以下会发生吗？

用 Emulator 能复制这问题吗？

谢谢。

**Comment by lantah-1** [comment]
i am also get this error on Android 10 (oneplus 6)

`java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:437)
        at android.content.ContentResolver.query(ContentResolver.java:962)
        at android.content.ContentResolver.query(ContentResolver.java:890)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) `

**Comment by ghost** [comment]
v0.5.3-beta3 try this version.

**Comment by haoqiangyu** [comment]
COUNT(*) AS 和 GROUP BY在Android 10 上用不了了

**Comment by zombiu** [comment]
> > 将版本更新到0.5.3-beta3后Android10不会发生崩溃，但红米上拍照不能返回照片数据，而是停留在选图页面。查询相册后也未查到任何照片，不建议使用拍照功能
> > 相机设置如下
> > .capture(true) // 使用相机，和 captureStrategy 一起使用
> > .captureStrategy( CaptureStrategy(true, String.format("%s.fileprovider", getPackageName())))
> 
> 你好。我之前做了些 Android Q 修复。可，我并没做大量测试。
> 
> 这问题只发生在特定机型吗？其他的机型呢？
> 
> 在 Android 9 或以下会发生吗？
> 
> 用 Emulator 能复制这问题吗？
> 
> 谢谢。

大佬，在红米7上拍照没反应，还停留在选图页面，这个解决了吗！android10一下测试下，没这个问题！

**Comment by ZYF99** [comment]
Android10 需要选两次图，才会返回

**Comment by ghost** [comment]
Try this version
implementation 'com.zhihu.android:matisse:0.5.3-beta3'

**Comment by victorfan336** [comment]
when will the 0.5.3 version be released ？
 @summerhotready @hetalkachhadiya 
thanks

**Comment by iyashamihsan** [comment]
implementation 'com.zhihu.android:matisse:0.5.3-beta3 
 worked for me ...

**Comment by DanteAndroid** [comment]
有没有临时解决方案？项目采用的是源码依赖，没法直接升级
