### ISSUE TITLE
【建议改进】处理 SDK 15 clipPath java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by yccheok** [zhihu/Matisse#781]
在 Android API 15，当点击左上角选项，我们得到以下异常

    Fatal Exception: java.lang.UnsupportedOperationException
           at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:408)
           at com.zhihu.matisse.internal.ui.widget.RoundedRectangleImageView.onDraw(RoundedRectangleImageView.java:62)
           at android.view.View.draw(View.java:10983)
           at android.view.View.getDisplayList(View.java:10422)
           at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
           at android.view.View.getDisplayList(View.java:10420)
           at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
           at android.widget.ListView.drawChild(ListView.java:3223)
           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
           at android.widget.AbsListView.dispatchDraw(AbsListView.java:2092)
           at android.widget.ListView.dispatchDraw(ListView.java:3218)
           at androidx.appcompat.widget.DropDownListView.dispatchDraw(DropDownListView.java:203)
           at android.view.View.draw(View.java:10986)
           at android.widget.AbsListView.draw(AbsListView.java:3398)
           at android.view.View.getDisplayList(View.java:10422)
           at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
           at android.view.View.draw(View.java:10986)
           at android.widget.FrameLayout.draw(FrameLayout.java:450)
           at android.view.View.getDisplayList(View.java:10422)
           at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:842)
           at android.view.ViewRootImpl.draw(ViewRootImpl.java:1910)
           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
           at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
           at android.os.Handler.dispatchMessage(Handler.java:99)
           at android.os.Looper.loop(Looper.java:137)
           at android.app.ActivityThread.main(ActivityThread.java:4429)
           at java.lang.reflect.Method.invokeNative(Method.java)
           at java.lang.reflect.Method.invoke(Method.java:511)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
           at dalvik.system.NativeStart.main(NativeStart.java)

我参考了

https://stackoverflow.com/questions/13248904/unsupportedoperationexception-on-clippath

我测试了，用 `setLayerType` 并不能很好的解决。我建议一律采用

    @Override
    protected void onDraw(Canvas canvas) {
        try {
            canvas.clipPath(mRoundedRectPath);
        } catch (java.lang.UnsupportedOperationException e) {
            Log.e(TAG, "", e);
        }

        super.onDraw(canvas);
    }

如有兴趣，我很乐意提交拉取请求。

谢谢

**Comment by mafanwei** [comment]
感觉项目不怎么维护了，老哥新开项目吧，可以一起维护
