### ISSUE TITLE
 Attempted to access a cursor after it has been closed

### ISSUE THREAD

**Issue by 494293346** [zhihu/Matisse#783]
在 0.5.2-beta3 ：

android.database.StaleDataException: Attempted to access a cursor after it has been closed.
    at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
    at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
    at android.content.ContentResolver.query(ContentResolver.java:877)
    at android.content.ContentResolver.query(ContentResolver.java:779)
    at android.content.ContentResolver.query(ContentResolver.java:737)
    at com.zhihu.matisse.internal.utils.PhotoMetadataUtils.b(PhotoMetadataUtils.java:112)
    at com.zhihu.matisse.MimeType.a(MimeType.java:141)
    at com.zhihu.matisse.internal.utils.PhotoMetadataUtils.b(PhotoMetadataUtils.java:150)
    at com.zhihu.matisse.internal.utils.PhotoMetadataUtils.a(PhotoMetadataUtils.java:128)
    at com.zhihu.matisse.internal.model.SelectedItemCollection.d(SelectedItemCollection.java:197)
    at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.a(AlbumMediaAdapter.java:206)
    at com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.a(AlbumMediaAdapter.java:172)
    at com.zhihu.matisse.internal.ui.widget.MediaGrid.onClick(MediaGrid.java:71)
    at android.view.View.performClick(View.java:6312)
    at android.view.View$PerformClick.run(View.java:24927)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:192)
    at android.app.ActivityThread.main(ActivityThread.java:6790)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by 494293346** [comment]
手机 vivo x9s ，Android 版本 8.1

**Comment by 494293346** [comment]
手机 vivo x9s ，Android 版本 8.1，点击图片或者视频闪退

**Comment by HanJinLiang** [comment]
同样的报错，这库是没在更新了么
