### ISSUE TITLE
Android 10打开报错   

### ISSUE THREAD

**Issue by Borninthesun** [zhihu/Matisse#798]
2020-07-18 12:10:05.878 2811-3145/com.zhihu.matisse.sample E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.zhihu.matisse.sample, PID: 2811
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error - SQLITE_IOERR_SHORT_READ (Sqlite code 522 SQLITE_IOERR_SHORT_READ), (OS error - 2:No such file or directory)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:182)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:955)
        at android.content.ContentResolver.query(ContentResolver.java:891)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:159)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:42)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929)

**Comment by Borninthesun** [comment]
荣耀 COL AL10    Android 10,level 29 

CPU架构

arm64-v8a

**Comment by Borninthesun** [comment]
貌似是内存不足引起的

**Comment by yccheok** [comment]
因为我们在不久后，就得确保 Matisse 在 Android API 29 的稳定性。我们自行 fork 了个旁枝，来进行测试及修正。

https://github.com/yccheok/Matisse/tree/fork

您说的问题，我复制不到。我用 Android Emulator API 29 及 28，执行 Matisse 的 sample，进行粗略的测试。都复制不到您说的问题。

请提供更多详情，如何用 Matisse sample，在 Emulator 上复制这个问题。谢谢。

**Comment by iyashamihsan** [comment]
im also having the same issue

**Comment by sixsixla** [comment]
我也遇到了这个问题，android11版本，无论是真机还是模拟机上都有

**Comment by sixsixla** [comment]
补充报错log:
![image](https://user-images.githubusercontent.com/56339974/147828536-b62de90a-ae66-4d24-be1e-35a3b1cfb661.png)
