### ISSUE TITLE
Fatal Exception: android.database.StaleDataException: Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by yinyangwu** [zhihu/Matisse#800]
Fatal Exception: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
       at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
       at android.database.BulkCursorToCursorAdaptor.getCount(BulkCursorToCursorAdaptor.java:69)
       at android.database.CursorWrapper.getCount(CursorWrapper.java:60)
       at android.database.MergeCursor.getCount(MergeCursor.java:61)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at com.zhihu.matisse.ui.MatisseActivity$1.run(MatisseActivity.java:363)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:7055)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

麻烦有时间解决一下，v0.5.2，加个判断cursor的状态也行。

**Comment by lovelyelfpop** [comment]
这个库已经被放弃了

**Comment by yccheok** [comment]
因为我们在不久后，就得确保 Matisse 在 Android API 29 的稳定性。我们自行 fork 了个旁枝，来进行测试及修正。

https://github.com/yccheok/Matisse/tree/fork

您说的问题，我复制不到。我用 Android Emulator API 29 及 28，执行 Matisse 的 sample，进行粗略的测试。都复制不到您说的问题。

请提供更多详情，如何用 Matisse sample，在 Emulator 上复制这个问题。谢谢。
