### ISSUE TITLE
拍一张之后回显不了图片Unknown URL: content://media/ is hidden API

### ISSUE THREAD

**Issue by gobeyondmyself** [zhihu/Matisse#821]
拍一张照片直接点勾选uri返回content://com.**.**.fileprovider/images/***.png
用glide去加载，但是不显示.
2020-09-30 23:37:09.946 15104-10215/? E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalStateException: Unknown URL: content://media/ is hidden API
        at com.android.providers.media.MediaProvider.matchUri(MediaProvider.java:9296)
        at com.android.providers.media.MediaProvider.uncanonicalize(MediaProvider.java:2903)
        at com.android.providers.media.MediaProvider.safeUncanonicalize(MediaProvider.java:2965)
        at com.android.providers.media.MediaProvider.queryInternal(MediaProvider.java:3179)
        at com.android.providers.media.MediaProvider.query(MediaProvider.java:3146)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:277)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)

**Comment by chunwhite** [comment]
你的是否是 Android 10及以上版本出现得问题

**Comment by BeiHaiCoding** [comment]
> 你的是否是 Android 10及以上版本出现得问题

是android10的话，该如何解决

**Comment by gobeyondmyself** [comment]
我也不能准确告诉你问题所在，但目前我是解决了的。这是存储路径的问题。String filePath = getExternalFilesDir(Environment.DIRECTORY_PICTURES).getAbsoluteFile()
                                                +File.separator+"compressPicture";这是我用的存储路径。

**Comment by BeiHaiCoding** [comment]
> 我也不能准确告诉你问题所在，但目前我是解决了的。这是存储路径的问题。String filePath = getExternalFilesDir(Environment.DIRECTORY_PICTURES).getAbsoluteFile()
> +File.separator+"compressPicture";这是我用的存储路径。

谢谢，我已解决问题。我的问题是android10不能随意创建目录导致的

**Comment by gobeyondmyself** [comment]
我也不能准确告诉你问题所在，但目前我是解决了的。这是存储路径的问题。这是我目前所用的存储路径String filePath = getExternalFilesDir(Environment.DIRECTORY_PICTURES).getAbsoluteFile()
+File.separator+"compressPicture";是没问题的。
