### ISSUE TITLE
java.lang.IllegalArgumentException: Width and height must be Target#SIZE_ORIGINAL or > 0

### ISSUE THREAD

**Issue by didikeeLunaon** [zhihu/Matisse#84]
# build.grade
```
    ...
    compile 'com.zhihu.android:matisse:0.4.3'
    compile 'com.github.bumptech.glide:glide:3.7.0'
```

# full crash log
```
java.lang.IllegalArgumentException: Width and height must be Target#SIZE_ORIGINAL or > 0
                                                                       at com.bumptech.glide.GenericRequestBuilder.override(GenericRequestBuilder.java:564)
                                                                       at com.bumptech.glide.BitmapRequestBuilder.override(BitmapRequestBuilder.java:435)
                                                                       at com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:39)
                                                                       at com.zhihu.matisse.internal.ui.widget.PhotoGrid.setImage(PhotoGrid.java:112)
                                                                       at com.zhihu.matisse.internal.ui.widget.PhotoGrid.bindPhoto(PhotoGrid.java:80)
                                                                       at com.zhihu.matisse.internal.ui.adapter.AlbumPhotosAdapter.onBindViewHolder(AlbumPhotosAdapter.java:111)
                                                                       at com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:44)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-29 11:46:37.197 11265-11265/didikee.image2pdf E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:818)
                                                                       at android.view.View.layout(View.java:18799)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5952)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2627)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2343)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```
what's wrong?

**Comment by keluokeda** [comment]
so i am

**Comment by stephanepechard** [comment]
Same here

**Comment by stephanepechard** [comment]
I found that in `AlbumPhotosAdapter.java`, you lazy load `mImageResize` evaluating it against 0, but it seems to be initiated to -1, so it is never properly lazy loaded. Will try to see if I can fix it.

**Comment by stephanepechard** [comment]
Ok, this is not exactly this. I narrowed down the problem to the method `getImageResize()` of `AlbumPhotosAdapter.java`. The algorithm computing the image resize is buggy for me (on a M simulator). I get `mImageResize = 1` because `spanCount = 131`:

    private int getImageResize(Context context) {
        if (mImageResize == 0) {
            RecyclerView.LayoutManager lm = mRecyclerView.getLayoutManager();
            int spanCount = ((GridLayoutManager) lm).getSpanCount();
            int screenWidth = context.getResources().getDisplayMetrics().widthPixels;
            int availableWidth = screenWidth - context.getResources().getDimensionPixelSize(
                    R.dimen.photo_grid_spacing) * (spanCount - 1);
            mImageResize = availableWidth / spanCount;
            mImageResize = (int) (mImageResize * mSelectionSpec.thumbnailScale);
        }
        return mImageResize;
    }

Can anyone explain this?
Thanks

**Comment by stephanepechard** [comment]
FYI, I still have it in v0.5.0-alpha4.

**Comment by Arthur-Feng** [comment]
Shortly, the __gridExpectedSize__ you set is too small, set it bigger than __4dp__ or just don't set it.

It using screen width / gridExpectedSize to calculate spanCount. When actually get the ImageView width, it using screen width / spanCount to get grid width then subtract default grid spacing. That means if your gridExpectedSize is smaller then default grid spacing you will get a ImageView size less than zero.

The default grid spacing is 4dp in the lib, so you   can't set gridExpectedSize smaller than that.
