### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by tranthangbk55** [zhihu/Matisse#852]
java.lang.SecurityException: com.xxx.xxx has no access to content://media/external/images/media/1809
        at com.android.providers.media.MediaProvider.enforceCallingPermissionInternal(MediaProvider.java:7888)
        at com.android.providers.media.MediaProvider.enforceCallingPermission(MediaProvider.java:7805)
        at com.android.providers.media.MediaProvider.updateInternal(MediaProvider.java:5428)
        at com.android.providers.media.MediaProvider.update(MediaProvider.java:5329)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:231)
        at android.os.Binder.execTransactInternal(Binder.java:1161)
        at android.os.Binder.execTransact(Binder.java:1130)

**Comment by kystudio** [comment]
> java.lang.SecurityException: com.xxx.xxx has no access to content://media/external/images/media/1809
> at com.android.providers.media.MediaProvider.enforceCallingPermissionInternal(MediaProvider.java:7888)
> at com.android.providers.media.MediaProvider.enforceCallingPermission(MediaProvider.java:7805)
> at com.android.providers.media.MediaProvider.updateInternal(MediaProvider.java:5428)
> at com.android.providers.media.MediaProvider.update(MediaProvider.java:5329)
> at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
> at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:231)
> at android.os.Binder.execTransactInternal(Binder.java:1161)
> at android.os.Binder.execTransact(Binder.java:1130)

我也遇到这问题了，请问你解决了吗？

**Comment by dstd** [comment]
@kystudio did you solved the issue? 😅

**Comment by kystudio** [comment]
> [@kystudio](https://github.com/kystudio) did you solved the issue? 😅

no
