### ISSUE TITLE
Matisse error app crashes- android.content.ActivityNotFoundException: Unable to find explicit activity class

### ISSUE THREAD

**Issue by KingsAGC** [zhihu/Matisse#872]
On Clicking pick images button in MainActivity my app crashes and errors Matisse library using 

android.content.ActivityNotFoundException: Unable to find explicit activity class {agc.pdf.maker/com.zhihu.matisse.ui.MatisseActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2078)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5377)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:584)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5335)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at com.zhihu.matisse.SelectionCreator.forResult(SelectionCreator.java:363)
	at agc.pdf.maker.MainActivity$3.onClick(MainActivity.java:266)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by kamaravichow** [comment]
Add below to your manifest file 

```xml
<activity android:name="com.zhihu.matisse.ui.MatisseActivity" />
<activity android:name="com.zhihu.matisse.internal.ui.AlbumPreviewActivity" />
<activity android:name="com.zhihu.matisse.internal.ui.SelectedPreviewActivity" />
```

Should fix the above error
