### ISSUE TITLE
java.lang.NullPointerException  拍照后奔溃，Android12

### ISSUE THREAD

**Issue by guo0842109** [zhihu/Matisse#885]
java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at android.media.MediaScannerConnection.lambda$scanFile$0$MediaScannerConnection(MediaScannerConnection.java:158)
	at android.media.MediaScannerConnection$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by guo0842109** [comment]
在开发者选项不保留活动的时候，打开拍照，必现

**Comment by yys730** [comment]
请问解决了吗？

**Comment by guo0842109** [comment]
> 请问解决了吗？

没有呢
